In [2]:
import pandas as pd
%pwd

'/home/kartik-agarwal/Documents/DialogGPT/ml/research/PytorchDemo'

In [30]:
import os
dataset_dir = os.path.join(os.getcwd(), '../artifacts/data_ingestion/')
total_data = 0
for file in os.listdir(dataset_dir):
    if file!= 'archive.zip':
        total_data +=len(pd.read_table(os.path.join(dataset_dir, file), encoding='latin1', on_bad_lines='skip'))
total_data

36790

In [85]:
import os
dataset_dir = os.path.join(os.getcwd(), '../artifacts/data_ingestion/')
data_frames = []
for file in os.listdir(dataset_dir):
    if file!= 'archive.zip':
        data_frames.append(pd.read_table(os.path.join(dataset_dir, file), header=None, encoding='latin1', on_bad_lines='skip'))
df = pd.concat(data_frames, ignore_index=True)

df

                                                       0
0                            Okay, hold on, don't shoot.
1                - You see where you're going? - Mm-hmm.
2                                                  Okay.
3              Now, let's worry about how you get there.
4                             Gotta move your foot here.
...                                                  ...
36808                                 - Mine. - Power...
36809                                     has a purpose.
36810                            Why are you doing this?
36811  Because I see, at long last, what's wrong with...
36812                                Too many sorcerers.

[36813 rows x 1 columns]

# Steps
- Data cleaning (regex)
- Create a Vocabulary
- Add <UNK>,<ST>,<ED> keywords in vocab
- Convert Dialogues to numerical embeddings
- Split each line for next word prediction
- Add padding
- do a test train split
- save the tensors for training on collab

In [86]:
import nltk

# Tokenization
nltk.download('punkt')
nltk.download('punkt_tab')

import torch
import torch.nn as nn
import torch.optim as optim
import numpy as np
from collections import Counter
from torch.utils.data import Dataset, DataLoader
from nltk.tokenize import word_tokenize

[nltk_data] Downloading package punkt to /home/kartik-
[nltk_data]     agarwal/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package punkt_tab to /home/kartik-
[nltk_data]     agarwal/nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!

In [87]:
import re
data_string = "".join(df.values.astype(str).flatten())
re.sub(r'\.', ' ',data_string)
data_string

'Okay, hold on, don\'t shoot.- You see where you\'re going? - Mm-hmm.Okay.Now, let\'s worry about how you get there.Gotta move your foot here.Point your toe this way.Your hips here.Okay?- Can you see? - Yeah.- Are you sure? - Mm-hmm.How about now? Can you see now?- No. - How about now?All right.Ready? Three fingers.Nice!Nice throw, kiddo.Here you go.Hey, you guys want mayo? Or mustard?Or both?Who puts mayo on a hot dog?Probably your brothers.Two mustard, please! Thanks, Mama.Got it!Nate, mayo or mustard?How about ketchup?Or ketchup. I got ketchup, too.Mind your elbow.Good job, hawk-eye.Go get your arrow.Hey, guys!Enough practice. Soup\'s on!All right.We\'re coming. We\'re hungry.Lila, let\'s go.Lila?Honey?Hey, babe?Babe?Babe?Boys!Boys!Laura!You don\'t need to do that.Because you\'re just holding the position.Oh, yeah.That was close.That\'s a goal. We are now one apiece.I would like to try again.We\'re tied up. Feel the tension?It\'s fun.That was terrible. Now you have a chance to win.And you\'ve won.Congratulations.Fair game.Good sport.You have fun?It was fun.This thing on?Hey, Miss Potts. Pep.If you find this recording...don\'t post it on social media.It\'s gonna be a real tearjerker.I don\'t know if you\'re ever gonna see these.I don\'t even know if you\'re still...Oh, God, I hope so.Today\'s day 21.No, 22.You know, if it wasn\'t for the existential terror...of staring into the literal void of space, I\'d say I\'m feeling a little better today.Infection\'s run its course, thanks to the Blue Meanie back there.You\'d love her.Very practical.Only a tiny bit sadistic.So, the fuel cells were cracked during battle...and we figured out a way to reverse the ion charge...and bought ourselves about 48 hours of flight time.But it\'s now dead in the water.Thousand light years from the nearest 7-Eleven.Oxygen will run out tomorrow morning...and that\'ll be it.Pep, I know I said no more surprises...but I got to say I was really hoping to pull off one last one.But it looks like...Well, you know what it looks like.Don\'t feel bad about this.I mean, actually, if you grovel for a couple weeks...and then move on with enormous guilt...I should probably lie down for a minute. Go rest my eyes.Please know...when I drift off, it\'ll be like every night lately.I\'m fine. Totally fine.I dream about you.Because it\'s always you.Couldn\'t stop him.Neither could I.Hang on.I lost the kid.Tony, we lost.Is...?- Oh, good. - Oh, my God!Oh, my God!It\'s okay.It\'s been 23 days since Thanos came to Earth.World governments are in pieces.The parts that are still working...are trying to take a census and it looks like he did...He did exactly what he said he was gonna do.Thanos wiped out...50% of all living creatures.Where is he now? Where?We don\'t know.He just opened a portal and walked through.What\'s wrong with him?He\'s pissed.He thinks he failed.Which, of course, he did...but there\'s a lot of that going around, ain\'t there?Honestly, until this exact second I thought you were a Build-A-Bear.Maybe I am.We\'ve been hunting Thanos for three weeks now.Deep space scans...and satellites, and we got nothing.Tony, you fought him.Who told you that?I didn\'t fight him.No, he wiped my face with a planet...while the Bleecker Street magician gave away the store.That\'s what happened. There was no fight, \'cause he\'s not beatable.Did he give you any clues, any coordinates, anything?I saw this coming a few years back.I had a vision. I didn\'t wanna believe it.Thought I was dreaming.Tony, I\'m gonna need you to focus.And I needed you.As in, past tense.That trumps what you need. It\'s too late, buddy.Sorry.You know what I need? I need a shave.And I believe I remember telling all youse...Tony, Tony!Alive and otherwise, that what we needed was a suit of armor around the world.Remember that? Whether it impacted our precious freedoms or not.That\'s what we needed.Well, that didn\'t work out, did it?I said we\'d lose.You said, "We\'ll do that together, too."And guess what, Cap?We lost.And you weren\'t there.But that\'s what we do, right?Our best work after the fact? We\'re the "Avengers."We\'re the "Avengers," not the "Pre-vengers."- Okay. - Right?You made your point. Just sit down, okay?Okay. No, no, here\'s my point. You know what?- She\'s great by the way. - Tony, you\'re sick. Sit down.We need you. You\'re new blood.Bunch of tired old mules. I got nothing for you, Cap.I got no coordinates...no clues, no strategies, no options.Zero. Zip. Nada.No trust, liar.Here, take this.You find him, you put that on...you hide.- Tony! - I\'m fine.Let me...Bruce gave him a sedative.He\'s gonna probably be out for the rest of the day.You guys take care of him...and I\'ll bring him a Xorrian elixir when I come back.Where are you going?To kill Thanos.Hey.You know, we usually work as a team here...and, between you and I, morale\'s a little fragile.We realize up there is more your territory, but this is our fight, too.You even know where he is?I know people who might.Don\'t bother.I can tell you where Thanos is.Thanos spent a long time trying to perfect me.And when he worked, he talked about his Great Plan.Even disassembled, I wanted to please him.I\'d ask...where would we go once his plan was complete?And his answer was always the same.To the Garden.That\'s cute. Thanos has a retirement plan.So, where is he?When Thanos snapped his fingers...Earth became ground zero for a power surge of ridiculously cosmic proportions.No one\'s ever seen anything like it.Until two days ago...on this planet.Thanos is there.He used the stones again.Hey, hey, hey.We\'d be going in shorthanded, you know?Look, he\'s still got the stones, so...So, let\'s get \'em.Use them to bring everyone back.Just like that?Yeah. Just like that.Even if there\'s a small chance that we can undo this...I mean, we owe it to everyone who\'s not in this room to try.If we do this, how do we know it\'s gonna end any differently than it did before?Because before you didn\'t have me.Hey, new girl?Everybody in this room is about that superhero life.And if you don\'t mind my asking, where the hell have you been all this time?There are a lot of other planets in the universe.And unfortunately, they didn\'t have you guys.I like this one.Let\'s go get this son of a bitch.Okay.Who here hasn\'t been to space?Why?You better not throw up on my ship.Approaching jump in three...two, one.I\'ll head down for recon.This is gonna work, Steve.I know it will.\'Cause I don\'t know what I\'m gonna do if it doesn\'t.No satellites. No ships. No armies.No ground defenses of any kind.It\'s just him.And that\'s enough.Oh, no.Where are they?Answer the question.The universe required correction.After that, the stones served no purpose...beyond temptation.You murdered trillions!You should be grateful.Where are the stones?Gone.Reduced to atoms.You used them two days ago!I used the stones to destroy the stones.It nearly killed me.But the work is done.It always will be.I am inevitable.We have to tear this place apart. He has to be lying!My father is many things.A liar is not one of them.Thank you, daughter.Perhaps I treated you too harshly.What?What did you do?I went for the head.So...I went on a date the other day.It\'s the first time in five years.You know? I\'m sitting there at dinner.I didn\'t even know what to talk about.What did you talk about?Same old crap. You know, how things have changed.My job, his job.How much we miss the Mets.And then things got quiet...then he cried as they were serving the salads.What about you?I cried just before dessert.But I\'m seeing him again tomorrow, so...That\'s great.You did the hardest part. You took the jump.You didn\'t know where you were gonna come down.And that\'s it. That\'s those little brave baby steps we got to take...to try and become whole again, try and find purpose.I went in the ice in \'45, right after I met the love of my life.Woke up 70 years later.You got to move on.Gotta move on.The world is in our hands.It\'s left to us, guys.And we got to do something with it.Otherwise...Thanos should\'ve killed all of us.What the hell?Hope?Kid!Hey, kid!What the hell happened here?Oh, my God!Oh, please!Please, please!No, no, no. No.No.Excuse me. Sorry.Cassie, no.No, no, no.No, no.Please, please, please. No, Cassie.What?Cassie?Dad?You\'re so big!Yeah. We boarded that highly-suspect warship Danvers pinged.It was an infectious garbage scow.So, thanks for the hot tip.Well, you were closer.Yeah. And now we smell like garbage.You get a reading on those tremors?\'Twas a mild subduction under the African plate.Do we have a visual? How are we handling it?Nat.It\'s an earthquake under the ocean.We handle it by not handling it.Carol, are we seeing you here next month?- Not likely. - What? You gonna get another haircut?Listen, fur face.I\'m covering a lot of territory.The things that are happening on Earth are happening everywhere.On thousands of planets.All right, all right. That\'s a good point. That\'s a good point.So, you might not see me for a long time.All right. Well...This channel\'s always active.So, if anything goes sideways...anyone\'s making trouble where they shouldn\'t...comes through me.Okay.All right.Good luck.Where are you?Mexico.The Federales found a room full of bodies.Looks like a bunch of cartel guys...never even had a chance to get their guns off.It\'s probably a rival gang.Except it isn\'t.It\'s definitely Barton.What he\'s done here...what he\'s been doing for the last few years...I mean, the scene that he left...I got to tell you, there\'s a part of me that doesn\'t even wanna find him.Will you find out where he\'s going next?Nat?Please?Okay.You know, I\'d offer to cook you dinner...but you seem pretty miserable already.You here to do your laundry?And to see a friend.Clearly, your friend is fine.You know, I saw a pod of whales when I was coming over the bridge.- In the Hudson? - There\'s fewer ships...cleaner water.You know, if you\'re about to tell me to look on the bright side...I\'m about to hit you in the head with a peanut butter sandwich.Sorry.Force of habit.You know, I keep telling everybody they should move on...and grow.Some do.But not us.If I move on, who does this?Maybe it doesn\'t need to be done.I used to have nothing.And then I got this.This job.This family.And I was better because of it.And even though they\'re gone...I\'m still trying to be better.I think we both need to get a life.You first.Hi, hi! Is anyone home?This is Scott Lang.We met a few years ago at the airport...in Germany?I was the guy that got really big. I had a mask on.- You wouldn\'t recognize me. - Is this an old message?Ant-Man? I know you know that.- It\'s the front gate. - I really need to talk to you guys.Scott.Are you okay?Yeah.Have either of you guys ever studied quantum physics?Only to make conversation.All right, so...five years ago, right before...Thanos...I was in a place called the quantum realm.The quantum realm is like its own microscopic universe.To get in there, you have to be incredibly small.Hope. She\'s my...She was my...She was supposed to pull me out.And then Thanos happened...and I got stuck in there.I\'m sorry, that must have been a very long five years.Yeah, but that\'s just it.It wasn\'t.For me, it was five hours.See, the rules of the quantum realm aren\'t like they are up here.Everything is unpredictable.Is that anybody\'s sandwich?I\'m starving.Scott.What are you talking about?So...what I\'m saying is...time works differently in the quantum realm.The only problem is right now we don\'t have a way to navigate it.But what if we did?I can\'t stop thinking about it. What if we could somehow control the chaos...and we could navigate it?What if there was a way...that we could enter the quantum realm at a certain point in time...but then exit the quantum realm at another point in time?Like...- Like before Thanos. - Wait.Are you talking about a time machine?No. No, of course not. No, not a time machine.This is more like a...Yeah. Like a time machine.I know, it\'s crazy. It\'s crazy.But I can\'t stop thinking about it. There\'s got to be...some way...- It\'s crazy. - Scott.I get emails from a raccoon...so nothing sounds crazy anymore.So, who do we talk to about this?Chow time!Maguna.Morgan H. Stark, you want some lunch?- Define "lunch" or be disintegrated. - Okay.You should not be wearing that, okay?That is part of a special anniversary gift I\'m making for Mom.There you go. You thinking about lunch?I can give you a handful of crickets on a bed of lettuce.- No. - That\'s what you want.How did you find this?- Garage. - Really?- Were you looking for it? - No.I found it, though.You like going in the garage, huh?So does Daddy.It\'s fine, actually. Mom never wears anything I buy her.So, I\'m gonna...No. We know what it sounds like.Tony, after everything you\'ve seen, is anything really impossible?Quantum fluctuation messes with the Planck Scale...which then triggers the Deutsch Proposition. Can we agree on that?Thank you.In layman\'s terms, it means you\'re not coming home.- I did. - No.You accidentally survived.It\'s a billion-to-one cosmic fluke.And now you wanna pull a... What do you call it?A time heist?Yeah, a time heist. Of course. Why didn\'t we think of this before?Oh, because it\'s laughable. Because it\'s a pipe dream.The stones are in the past. We could go back, we could get them.We can snap our own fingers. We can bring everybody back.Or screw it up worse than he already has, right?I don\'t believe we would.Gotta say it. I sometimes miss that giddy optimism.However, high hopes won\'t help...if there\'s no logical, tangible way for me to safely execute said time heist.I believe the most likely outcome will be our collective demise.Not if we strictly follow the rules of time travel.All right? It means no talking to our past selves...no betting on sporting events.I\'m gonna stop you right there, Scott.Are you seriously telling me that your plan to save the universe...is based on Back to the Future?- Is it? - No.Good. You had me worried there. \'Cause that would be horseshit.That\'s not how quantum physics works.Tony.We have to take a stand.We did stand. And yet, here we are.I know you got a lot on the line.You got a wife, a daughter.But I lost someone very important to me.A lotta people did.And now, now we have a chance to bring her back...to bring everyone back, and you\'re telling me that you won\'t even...That\'s right, Scott. I won\'t even.I can\'t.Mommy told me to come and save you.Good job. I\'m saved.I wish you were coming here to ask me something else. Anything else.I\'m honestly happy to see you guys, I just...- Oh, look, the table\'s set for six. - Tony.I get it.And I\'m happy for you. I really am.But this is a second chance.I got my second chance right here, Cap.Can\'t roll the dice on it.If you don\'t talk shop, you can stay for lunch.Well, he\'s scared.He\'s not wrong.Yeah, but, I mean, what are we gonna do?We need him. What, are we gonna stop?No, I wanna do it right.We\'re gonna need a really big brain.Bigger than his?Come on, I feel like I\'m the only one eating here. Try some of that.Have some eggs.I\'m so confused.These are confusing times.Right, no, no. That\'s not what I meant.Nah, I get it. I\'m kidding!I know, it\'s crazy.I\'m wearing shirts now.Yeah. What? How? Why?Five years ago, we got our asses beat.Except it was worse for me...\'cause I lost twice.First, Hulk lost, then Banner lost...and then, we all lost.No one blamed you, Bruce.I did.For years, I\'ve been treating the Hulk like he\'s some kind of disease...something to get rid of.But then, I start looking at him as the cure.Eighteen months in the gamma lab.I put the brains and the brawn together...and now, look at me.Best of both worlds.- Excuse me, Mr. Hulk? - Yes.Can we get a photo?100%, little person.Come on, step on up. Do you mind?- Oh, yeah, yeah. - Thanks.Say "green."- Green. - Green.Did you get that?That\'s a good one.Did you want to grab one with me? I\'m Ant-Man.They\'re Hulk fans. They don\'t know Ant-Man.Nobody does.- No, he wants you to take a picture with him. - I don\'t want a picture.Stranger danger.Yeah, look, he\'s even saying no, he doesn\'t.- I get it. I don\'t want it, either. - But come on. The kid...I don\'t want a picture with them.- He\'s gonna feel bad. - Sorry.They\'re happy to do it. They said they\'ll do it.- I don\'t want to do it. - We can do it.- No, you feel bad. - Take the goddamn phone.Okay.- Thank you, Mr. Hulk. - No, it was great, kids. Thank you very much.Hulk out!Bruce.Dab.- Bruce. - Listen to your mom.She knows better.About what we were saying.Right.The whole time travel do-over?Guys, it\'s outside of my area of expertise.Well, you pulled this off.I remember a time when that seemed pretty impossible, too.I\'ve got a mild inspiration. I\'d like to see if it checks out.So, I\'d like to run one last sim before we pack it in for the night.This time, in the shape of a Mobius strip, inverted, please.Processing.Right, give me the eigenvalue of that particle...factoring in spectral decomp.- That\'ll take a second. - Just a moment.And don\'t worry if it doesn\'t pan out. I\'m just kinda...Model rendered.Shit!Shit!What are you doing up, little miss?- Shit. - Nope. We don\'t say that.Only Mommy says that word.She coined it. It belongs to her.Why are you up?\'Cause I\'ve got some important shit going on here!Why do you think?No, I got something on my mind. I got something on my mind.Was it juice pops?Sure was.That\'s extortion. That\'s a word.What kind you want?Great minds think alike.Juice pops exactly...was on my mind.You done? Yeah?Now you are.Here. Wipe.Good. That face goes there.Tell me a story.A story.Once upon a time, Maguna went to bed. The end.That is a horrible story.Come on, that\'s your favorite story.Love you tons.I love you 3,000.Wow.3,000. That\'s crazy.Go to bed or I\'ll sell all your toys.Night night.Not that it\'s a competition...but she loves me 3,000.Does she, now?You were somewhere in the low 6 to 900 range.Whatcha reading?Just a book on composting.What\'s new with composting?- Interesting science... - I figured it out.By the way.And, you know, just so we\'re talking about the same thing...Time travel.What?Wow.That\'s amazing...and terrifying.That\'s right.We got really lucky.Yeah.I know.A lot of people didn\'t.Nope. And I can\'t help everybody.Sorta seems like you can.Not if I stop.I can put a pin in it right now and stop.Tony...trying to get you to stop...has been one of the few failures of my entire life.Something tells me...I should put it in a lockbox and drop it to the bottom of the lake...and go to bed.But would you be able to rest?Okay, here we go. Time travel test number one.Scott, fire up...the van thing.Breakers are set.Emergency generators are on standby.Good, because if we blow the grid, I don\'t want to lose Tiny here in the 1950s.Excuse me?He\'s kidding.You can\'t say things like that.It was a bad joke.You were kidding, right?I have no idea. We\'re talking about time travel here.Either it\'s all a joke, or none of it is.We\'re good!Get your helmet on.Scott, I\'m gonna send you back a week...let you walk around for an hour, then bring you back in 10 seconds.Make sense?Perfectly not confusing.Good luck, Scott. You got this.You\'re right. I do, Captain America.On a count of three...Three, two, one.Guys?This doesn\'t feel right.What is this?- What\'s going on? - Who is that?- Hold on. - Is that Scott?Yes, it\'s Scott.- What\'s going on, Bruce? - Oh, my back!- What is this? - Hold on a second.- Could I get a little space here? - Yeah, yeah, yeah.- Can you bring him back? - I\'m working on it.It\'s a baby.- It\'s Scott. - As a baby.- He\'ll grow. - Bring Scott back.When I say kill the power, kill the power.Oh, my God.And... kill it!Somebody peed my pants.Oh, thank God.But I don\'t know if it was baby me or old me.Or just me me.Time travel!What?I see this as an absolute win.Why the long face?Let me guess, he turned into a baby.Among other things, yeah. What are you do

In [88]:
def clean_text(text):
    if not isinstance(text, str):
        text = str(text)

    # 1. Keep letters, numbers, spaces, and core punctuation (. , ! ? ')
    # [^a-zA-Z0-9\s.,!?'] means "remove everything EXCEPT these"
    text = re.sub(r"[^a-zA-Z0-9\s.,!?']", " ", text)

    # 2. Fix the apostrophe issue (keep it between letters)
    # This removes ' if it's just hanging at the start/end of a word
    text = re.sub(r"(?<!\w)'|'(?!\w)", " ", text)

    # 3. Standardize whitespace
    text = text.lower()
    text = re.sub(r'\s+', ' ', text).strip()

    return text


df[0] = df[0].apply(clean_text)
df.head()

                                           0
0                okay, hold on, don't shoot.
1        you see where you're going? mm hmm.
2                                      okay.
3  now, let's worry about how you get there.
4                 gotta move your foot here.

In [89]:
data_string = clean_text(data_string)
data_string

"okay, hold on, don't shoot. you see where you're going? mm hmm.okay.now, let's worry about how you get there.gotta move your foot here.point your toe this way.your hips here.okay? can you see? yeah. are you sure? mm hmm.how about now? can you see now? no. how about now?all right.ready? three fingers.nice!nice throw, kiddo.here you go.hey, you guys want mayo? or mustard?or both?who puts mayo on a hot dog?probably your brothers.two mustard, please! thanks, mama.got it!nate, mayo or mustard?how about ketchup?or ketchup. i got ketchup, too.mind your elbow.good job, hawk eye.go get your arrow.hey, guys!enough practice. soup's on!all right.we're coming. we're hungry.lila, let's go.lila?honey?hey, babe?babe?babe?boys!boys!laura!you don't need to do that.because you're just holding the position.oh, yeah.that was close.that's a goal. we are now one apiece.i would like to try again.we're tied up. feel the tension?it's fun.that was terrible. now you have a chance to win.and you've won.congratulations.fair game.good sport.you have fun?it was fun.this thing on?hey, miss potts. pep.if you find this recording...don't post it on social media.it's gonna be a real tearjerker.i don't know if you're ever gonna see these.i don't even know if you're still...oh, god, i hope so.today's day 21.no, 22.you know, if it wasn't for the existential terror...of staring into the literal void of space, i'd say i'm feeling a little better today.infection's run its course, thanks to the blue meanie back there.you'd love her.very practical.only a tiny bit sadistic.so, the fuel cells were cracked during battle...and we figured out a way to reverse the ion charge...and bought ourselves about 48 hours of flight time.but it's now dead in the water.thousand light years from the nearest 7 eleven.oxygen will run out tomorrow morning...and that'll be it.pep, i know i said no more surprises...but i got to say i was really hoping to pull off one last one.but it looks like...well, you know what it looks like.don't feel bad about this.i mean, actually, if you grovel for a couple weeks...and then move on with enormous guilt...i should probably lie down for a minute. go rest my eyes.please know...when i drift off, it'll be like every night lately.i'm fine. totally fine.i dream about you.because it's always you.couldn't stop him.neither could i.hang on.i lost the kid.tony, we lost.is...? oh, good. oh, my god!oh, my god!it's okay.it's been 23 days since thanos came to earth.world governments are in pieces.the parts that are still working...are trying to take a census and it looks like he did...he did exactly what he said he was gonna do.thanos wiped out...50 of all living creatures.where is he now? where?we don't know.he just opened a portal and walked through.what's wrong with him?he's pissed.he thinks he failed.which, of course, he did...but there's a lot of that going around, ain't there?honestly, until this exact second i thought you were a build a bear.maybe i am.we've been hunting thanos for three weeks now.deep space scans...and satellites, and we got nothing.tony, you fought him.who told you that?i didn't fight him.no, he wiped my face with a planet...while the bleecker street magician gave away the store.that's what happened. there was no fight, cause he's not beatable.did he give you any clues, any coordinates, anything?i saw this coming a few years back.i had a vision. i didn't wanna believe it.thought i was dreaming.tony, i'm gonna need you to focus.and i needed you.as in, past tense.that trumps what you need. it's too late, buddy.sorry.you know what i need? i need a shave.and i believe i remember telling all youse...tony, tony!alive and otherwise, that what we needed was a suit of armor around the world.remember that? whether it impacted our precious freedoms or not.that's what we needed.well, that didn't work out, did it?i said we'd lose.you said, we'll do that together, too. and guess what, cap?we lost.and you weren't there.but that's what we do, right?our best work after the fact? we're the avengers. we're the avengers, not the pre vengers. okay. right?you made your point. just sit down, okay?okay. no, no, here's my point. you know what? she's great by the way. tony, you're sick. sit down.we need you. you're new blood.bunch of tired old mules. i got nothing for you, cap.i got no coordinates...no clues, no strategies, no options.zero. zip. nada.no trust, liar.here, take this.you find him, you put that on...you hide. tony! i'm fine.let me...bruce gave him a sedative.he's gonna probably be out for the rest of the day.you guys take care of him...and i'll bring him a xorrian elixir when i come back.where are you going?to kill thanos.hey.you know, we usually work as a team here...and, between you and i, morale's a little fragile.we realize up there is more your territory, but this is our fight, too.you even know where he is?i know people who might.don't bother.i can tell you where thanos is.thanos spent a long time trying to perfect me.and when he worked, he talked about his great plan.even disassembled, i wanted to please him.i'd ask...where would we go once his plan was complete?and his answer was always the same.to the garden.that's cute. thanos has a retirement plan.so, where is he?when thanos snapped his fingers...earth became ground zero for a power surge of ridiculously cosmic proportions.no one's ever seen anything like it.until two days ago...on this planet.thanos is there.he used the stones again.hey, hey, hey.we'd be going in shorthanded, you know?look, he's still got the stones, so...so, let's get em.use them to bring everyone back.just like that?yeah. just like that.even if there's a small chance that we can undo this...i mean, we owe it to everyone who's not in this room to try.if we do this, how do we know it's gonna end any differently than it did before?because before you didn't have me.hey, new girl?everybody in this room is about that superhero life.and if you don't mind my asking, where the hell have you been all this time?there are a lot of other planets in the universe.and unfortunately, they didn't have you guys.i like this one.let's go get this son of a bitch.okay.who here hasn't been to space?why?you better not throw up on my ship.approaching jump in three...two, one.i'll head down for recon.this is gonna work, steve.i know it will. cause i don't know what i'm gonna do if it doesn't.no satellites. no ships. no armies.no ground defenses of any kind.it's just him.and that's enough.oh, no.where are they?answer the question.the universe required correction.after that, the stones served no purpose...beyond temptation.you murdered trillions!you should be grateful.where are the stones?gone.reduced to atoms.you used them two days ago!i used the stones to destroy the stones.it nearly killed me.but the work is done.it always will be.i am inevitable.we have to tear this place apart. he has to be lying!my father is many things.a liar is not one of them.thank you, daughter.perhaps i treated you too harshly.what?what did you do?i went for the head.so...i went on a date the other day.it's the first time in five years.you know? i'm sitting there at dinner.i didn't even know what to talk about.what did you talk about?same old crap. you know, how things have changed.my job, his job.how much we miss the mets.and then things got quiet...then he cried as they were serving the salads.what about you?i cried just before dessert.but i'm seeing him again tomorrow, so...that's great.you did the hardest part. you took the jump.you didn't know where you were gonna come down.and that's it. that's those little brave baby steps we got to take...to try and become whole again, try and find purpose.i went in the ice in 45, right after i met the love of my life.woke up 70 years later.you got to move on.gotta move on.the world is in our hands.it's left to us, guys.and we got to do something with it.otherwise...thanos should've killed all of us.what the hell?hope?kid!hey, kid!what the hell happened here?oh, my god!oh, please!please, please!no, no, no. no.no.excuse me. sorry.cassie, no.no, no, no.no, no.please, please, please. no, cassie.what?cassie?dad?you're so big!yeah. we boarded that highly suspect warship danvers pinged.it was an infectious garbage scow.so, thanks for the hot tip.well, you were closer.yeah. and now we smell like garbage.you get a reading on those tremors? twas a mild subduction under the african plate.do we have a visual? how are we handling it?nat.it's an earthquake under the ocean.we handle it by not handling it.carol, are we seeing you here next month? not likely. what? you gonna get another haircut?listen, fur face.i'm covering a lot of territory.the things that are happening on earth are happening everywhere.on thousands of planets.all right, all right. that's a good point. that's a good point.so, you might not see me for a long time.all right. well...this channel's always active.so, if anything goes sideways...anyone's making trouble where they shouldn't...comes through me.okay.all right.good luck.where are you?mexico.the federales found a room full of bodies.looks like a bunch of cartel guys...never even had a chance to get their guns off.it's probably a rival gang.except it isn't.it's definitely barton.what he's done here...what he's been doing for the last few years...i mean, the scene that he left...i got to tell you, there's a part of me that doesn't even wanna find him.will you find out where he's going next?nat?please?okay.you know, i'd offer to cook you dinner...but you seem pretty miserable already.you here to do your laundry?and to see a friend.clearly, your friend is fine.you know, i saw a pod of whales when i was coming over the bridge. in the hudson? there's fewer ships...cleaner water.you know, if you're about to tell me to look on the bright side...i'm about to hit you in the head with a peanut butter sandwich.sorry.force of habit.you know, i keep telling everybody they should move on...and grow.some do.but not us.if i move on, who does this?maybe it doesn't need to be done.i used to have nothing.and then i got this.this job.this family.and i was better because of it.and even though they're gone...i'm still trying to be better.i think we both need to get a life.you first.hi, hi! is anyone home?this is scott lang.we met a few years ago at the airport...in germany?i was the guy that got really big. i had a mask on. you wouldn't recognize me. is this an old message?ant man? i know you know that. it's the front gate. i really need to talk to you guys.scott.are you okay?yeah.have either of you guys ever studied quantum physics?only to make conversation.all right, so...five years ago, right before...thanos...i was in a place called the quantum realm.the quantum realm is like its own microscopic universe.to get in there, you have to be incredibly small.hope. she's my...she was my...she was supposed to pull me out.and then thanos happened...and i got stuck in there.i'm sorry, that must have been a very long five years.yeah, but that's just it.it wasn't.for me, it was five hours.see, the rules of the quantum realm aren't like they are up here.everything is unpredictable.is that anybody's sandwich?i'm starving.scott.what are you talking about?so...what i'm saying is...time works differently in the quantum realm.the only problem is right now we don't have a way to navigate it.but what if we did?i can't stop thinking about it. what if we could somehow control the chaos...and we could navigate it?what if there was a way...that we could enter the quantum realm at a certain point in time...but then exit the quantum realm at another point in time?like... like before thanos. wait.are you talking about a time machine?no. no, of course not. no, not a time machine.this is more like a...yeah. like a time machine.i know, it's crazy. it's crazy.but i can't stop thinking about it. there's got to be...some way... it's crazy. scott.i get emails from a raccoon...so nothing sounds crazy anymore.so, who do we talk to about this?chow time!maguna.morgan h. stark, you want some lunch? define lunch or be disintegrated. okay.you should not be wearing that, okay?that is part of a special anniversary gift i'm making for mom.there you go. you thinking about lunch?i can give you a handful of crickets on a bed of lettuce. no. that's what you want.how did you find this? garage. really? were you looking for it? no.i found it, though.you like going in the garage, huh?so does daddy.it's fine, actually. mom never wears anything i buy her.so, i'm gonna...no. we know what it sounds like.tony, after everything you've seen, is anything really impossible?quantum fluctuation messes with the planck scale...which then triggers the deutsch proposition. can we agree on that?thank you.in layman's terms, it means you're not coming home. i did. no.you accidentally survived.it's a billion to one cosmic fluke.and now you wanna pull a... what do you call it?a time heist?yeah, a time heist. of course. why didn't we think of this before?oh, because it's laughable. because it's a pipe dream.the stones are in the past. we could go back, we could get them.we can snap our own fingers. we can bring everybody back.or screw it up worse than he already has, right?i don't believe we would.gotta say it. i sometimes miss that giddy optimism.however, high hopes won't help...if there's no logical, tangible way for me to safely execute said time heist.i believe the most likely outcome will be our collective demise.not if we strictly follow the rules of time travel.all right? it means no talking to our past selves...no betting on sporting events.i'm gonna stop you right there, scott.are you seriously telling me that your plan to save the universe...is based on back to the future? is it? no.good. you had me worried there. cause that would be horseshit.that's not how quantum physics works.tony.we have to take a stand.we did stand. and yet, here we are.i know you got a lot on the line.you got a wife, a daughter.but i lost someone very important to me.a lotta people did.and now, now we have a chance to bring her back...to bring everyone back, and you're telling me that you won't even...that's right, scott. i won't even.i can't.mommy told me to come and save you.good job. i'm saved.i wish you were coming here to ask me something else. anything else.i'm honestly happy to see you guys, i just... oh, look, the table's set for six. tony.i get it.and i'm happy for you. i really am.but this is a second chance.i got my second chance right here, cap.can't roll the dice on it.if you don't talk shop, you can stay for lunch.well, he's scared.he's not wrong.yeah, but, i mean, what are we gonna do?we need him. what, are we gonna stop?no, i wanna do it right.we're gonna need a really big brain.bigger than his?come on, i feel like i'm the only one eating here. try some of that.have some eggs.i'm so confused.these are confusing times.right, no, no. that's not what i meant.nah, i get it. i'm kidding!i know, it's crazy.i'm wearing shirts now.yeah. what? how? why?five years ago, we got our asses beat.except it was worse for me... cause i lost twice.first, hulk lost, then banner lost...and then, we all lost.no one blamed you, bruce.i did.for years, i've been treating the hulk like he's some kind of disease...something to get rid of.but then, i start looking at him as the cure.eighteen months in the gamma lab.i put the brains and the brawn together...and now, look at me.best of both worlds. excuse me, mr. hulk? yes.can we get a photo?100 , little person.come on, step on up. do you mind? oh, yeah, yeah. thanks.say green. green. green.did you get that?that's a good one.did you want to grab one with me? i'm ant man.they're hulk fans. they don't know ant man.nobody does. no, he wants you to take a picture with him. i don't want a picture.stranger danger.yeah, look, he's even saying no, he doesn't. i get it. i don't want it, either. but come on. the kid...i don't want a picture with them. he's gonna feel bad. sorry.they're happy to do it. they said they'll do it. i don't want to do it. we can do it. no, you feel bad. take the goddamn phone.okay. thank you, mr. hulk. no, it was great, kids. thank you very much.hulk out!bruce.dab. bruce. listen to your mom.she knows better.about what we were saying.right.the whole time travel do over?guys, it's outside of my area of expertise.well, you pulled this off.i remember a time when that seemed pretty impossible, too.i've got a mild inspiration. i'd like to see if it checks out.so, i'd like to run one last sim before we pack it in for the night.this time, in the shape of a mobius strip, inverted, please.processing.right, give me the eigenvalue of that particle...factoring in spectral decomp. that'll take a second. just a moment.and don't worry if it doesn't pan out. i'm just kinda...model rendered.shit!shit!what are you doing up, little miss? shit. nope. we don't say that.only mommy says that word.she coined it. it belongs to her.why are you up? cause i've got some important shit going on here!why do you think?no, i got something on my mind. i got something on my mind.was it juice pops?sure was.that's extortion. that's a word.what kind you want?great minds think alike.juice pops exactly...was on my mind.you done? yeah?now you are.here. wipe.good. that face goes there.tell me a story.a story.once upon a time, maguna went to bed. the end.that is a horrible story.come on, that's your favorite story.love you tons.i love you 3,000.wow.3,000. that's crazy.go to bed or i'll sell all your toys.night night.not that it's a competition...but she loves me 3,000.does she, now?you were somewhere in the low 6 to 900 range.whatcha reading?just a book on composting.what's new with composting? interesting science... i figured it out.by the way.and, you know, just so we're talking about the same thing...time travel.what?wow.that's amazing...and terrifying.that's right.we got really lucky.yeah.i know.a lot of people didn't.nope. and i can't help everybody.sorta seems like you can.not if i stop.i can put a pin in it right now and stop.tony...trying to get you to stop...has been one of the few failures of my entire life.something tells me...i should put it in a lockbox and drop it to the bottom of the lake...and go to bed.but would you be able to rest?okay, here we go. time travel test number one.scott, fire up...the van thing.breakers are set.emergency generators are on standby.good, because if we blow the grid, i don't want to lose tiny here in the 1950s.excuse me?he's kidding.you can't say things like that.it was a bad joke.you were kidding, right?i have no idea. we're talking about time travel here.either it's all a joke, or none of it is.we're good!get your helmet on.scott, i'm gonna send you back a week...let you walk around for an hour, then bring you back in 10 seconds.make sense?perfectly not confusing.good luck, scott. you got this.you're right. i do, captain america.on a count of three...three, two, one.guys?this doesn't feel right.what is this? what's going on? who is that? hold on. is that scott?yes, it's scott. what's going on, bruce? oh, my back! what is this? hold on a second. could i get a little space here? yeah, yeah, yeah. can you bring him back? i'm working on it.it's a baby. it's scott. as a baby. he'll grow. bring scott back.when i say kill the power, kill the power.oh, my god.and... kill it!somebody peed my pants.oh, thank god.but i don't know if it was baby me or old me.or just me me.time travel!what?i see this as an absolute win.why the long face?let me guess, he turned into a baby.among other things, yeah. what are you doing here?it's the epr paradox.instead of pushing lang through time, you might've wound up...pushing time through lang.it's tricky, dangerous. somebody could have cautioned you against it.you did.oh, did i?well, thank god i'm here.regardless, i fixed it.a fully functioning time space gps.i just want peace.turns out resentment is corrosive, and i hate it.me, too.we got a 

In [109]:

# build vocab
vocab = {'<unk>':0, 'start_token':1, 'end_token':2}
tokens = word_tokenize(data_string.lower())
for token in Counter(tokens).keys():
  if token not in vocab:
    vocab[token] = len(vocab)

vocab

{'<unk>': 0,
 'start_token': 1,
 'end_token': 2,
 'okay': 3,
 ',': 4,
 'hold': 5,
 'on': 6,
 'do': 7,
 "n't": 8,
 'shoot': 9,
 '.': 10,
 'you': 11,
 'see': 12,
 'where': 13,
 "'re": 14,
 'going': 15,
 '?': 16,
 'mm': 17,
 'hmm.okay.now': 18,
 'let': 19,
 "'s": 20,
 'worry': 21,
 'about': 22,
 'how': 23,
 'get': 24,
 'there.': 25,
 'got': 26,
 'ta': 27,
 'move': 28,
 'your': 29,
 'foot': 30,
 'here.point': 31,
 'toe': 32,
 'this': 33,
 'way.your': 34,
 'hips': 35,
 'here.okay': 36,
 'can': 37,
 'yeah': 38,
 'are': 39,
 'sure': 40,
 'hmm.how': 41,
 'now': 42,
 'no': 43,
 'all': 44,
 'right.ready': 45,
 'three': 46,
 'fingers.nice': 47,
 '!': 48,
 'nice': 49,
 'throw': 50,
 'kiddo.here': 51,
 'go.hey': 52,
 'guys': 53,
 'want': 54,
 'mayo': 55,
 'or': 56,
 'mustard': 57,
 'both': 58,
 'who': 59,
 'puts': 60,
 'a': 61,
 'hot': 62,
 'dog': 63,
 'probably': 64,
 'brothers.two': 65,
 'please': 66,
 'thanks': 67,
 'mama.got': 68,
 'it': 69,
 'nate': 70,
 'ketchup': 71,
 'i': 72,
 'too.mind': 73,
 'elbow.good': 74,
 'job': 75,
 'hawk': 76,
 'eye.go': 77,
 'arrow.hey': 78,
 'enough': 79,
 'practice': 80,
 'soup': 81,
 'right.we': 82,
 'coming': 83,
 'we': 84,
 'hungry.lila': 85,
 'go.lila': 86,
 'honey': 87,
 'hey': 88,
 'babe': 89,
 'boys': 90,
 'laura': 91,
 'need': 92,
 'to': 93,
 'that.because': 94,
 'just': 95,
 'holding': 96,
 'the': 97,
 'position.oh': 98,
 'yeah.that': 99,
 'was': 100,
 'close.that': 101,
 'goal': 102,
 'one': 103,
 'apiece.i': 104,
 'would': 105,
 'like': 106,
 'try': 107,
 'again.we': 108,
 'tied': 109,
 'up': 110,
 'feel': 111,
 'tension': 112,
 'fun.that': 113,
 'terrible': 114,
 'have': 115,
 'chance': 116,
 'win.and': 117,
 "'ve": 118,
 'won.congratulations.fair': 119,
 'game.good': 120,
 'sport.you': 121,
 'fun': 122,
 'fun.this': 123,
 'thing': 124,
 'miss': 125,
 'potts': 126,
 'pep.if': 127,
 'find': 128,
 'recording': 129,
 '...': 130,
 'post': 131,
 'social': 132,
 'media.it': 133,
 'gon': 134,
 'na': 135,
 'be': 136,
 'real': 137,
 'tearjerker.i': 138,
 'know': 139,
 'if': 140,
 'ever': 141,
 'these.i': 142,
 'even': 143,
 'still': 144,
 'oh': 145,
 'god': 146,
 'hope': 147,
 'so.today': 148,
 'day': 149,
 '21.no': 150,
 '22.you': 151,
 'for': 152,
 'existential': 153,
 'terror': 154,
 'of': 155,
 'staring': 156,
 'into': 157,
 'literal': 158,
 'void': 159,
 'space': 160,
 "'d": 161,
 'say': 162,
 "'m": 163,
 'feeling': 164,
 'little': 165,
 'better': 166,
 'today.infection': 167,
 'run': 168,
 'its': 169,
 'course': 170,
 'blue': 171,
 'meanie': 172,
 'back': 173,
 'there.you': 174,
 'love': 175,
 'her.very': 176,
 'practical.only': 177,
 'tiny': 178,
 'bit': 179,
 'sadistic.so': 180,
 'fuel': 181,
 'cells': 182,
 'were': 183,
 'cracked': 184,
 'during': 185,
 'battle': 186,
 'and': 187,
 'figured': 188,
 'out': 189,
 'way': 190,
 'reverse': 191,
 'ion': 192,
 'charge': 193,
 'bought': 194,
 'ourselves': 195,
 '48': 196,
 'hours': 197,
 'flight': 198,
 'time.but': 199,
 'dead': 200,
 'in': 201,
 'water.thousand': 202,
 'light': 203,
 'years': 204,
 'from': 205,
 'nearest': 206,
 '7': 207,
 'eleven.oxygen': 208,
 'will': 209,
 'tomorrow': 210,
 'morning': 211,
 'that': 212,
 "'ll": 213,
 'it.pep': 214,
 'said': 215,
 'more': 216,
 'surprises': 217,
 'but': 218,
 'really': 219,
 'hoping': 220,
 'pull': 221,
 'off': 222,
 'last': 223,
 'one.but': 224,
 'looks': 225,
 'well': 226,
 'what': 227,
 'like.do': 228,
 'bad': 229,
 'this.i': 230,
 'mean': 231,
 'actually': 232,
 'grovel': 233,
 'couple': 234,
 'weeks': 235,
 'then': 236,
 'with': 237,
 'enormous': 238,
 'guilt': 239,
 'should': 240,
 'lie': 241,
 'down': 242,
 'minute': 243,
 'go': 244,
 'rest': 245,
 'my': 246,
 'eyes.please': 247,
 'when': 248,
 'drift': 249,
 'every': 250,
 'night': 251,
 'lately.i': 252,
 'fine': 253,
 'totally': 254,
 'fine.i': 255,
 'dream': 256,
 'you.because': 257,
 'always': 258,
 'you.could': 259,
 'stop': 260,
 'him.neither': 261,
 'could': 262,
 'i.hang': 263,
 'on.i': 264,
 'lost': 265,
 'kid.tony': 266,
 'lost.is': 267,
 'good': 268,
 'okay.it': 269,
 'been': 270,
 '23': 271,
 'days': 272,
 'since': 273,
 'thanos': 274,
 'came': 275,
 'earth.world': 276,
 'governments': 277,
 'pieces.the': 278,
 'parts': 279,
 'working': 280,
 'trying': 281,
 'take': 282,
 'census': 283,
 'he': 284,
 'did': 285,
 'exactly': 286,
 'do.thanos': 287,
 'wiped': 288,
 '50': 289,
 'living': 290,
 'creatures.where': 291,
 'is': 292,
 'know.he': 293,
 'opened': 294,
 'portal': 295,
 'walked': 296,
 'through.what': 297,
 'wrong': 298,
 'him': 299,
 'pissed.he': 300,
 'thinks': 301,
 'failed.which': 302,
 'there': 303,
 'lot': 304,
 'around': 305,
 'ai': 306,
 'honestly': 307,
 'until': 308,
 'exact': 309,
 'second': 310,
 'thought': 311,
 'build': 312,
 'bear.maybe': 313,
 'am.we': 314,
 'hunting': 315,
 'now.deep': 316,
 'scans': 317,
 'satellites': 318,
 'nothing.tony': 319,
 'fought': 320,
 'him.who': 321,
 'told': 322,
 'fight': 323,
 'him.no': 324,
 'face': 325,
 'planet': 326,
 'while': 327,
 'bleecker': 328,
 'street': 329,
 'magician': 330,
 'gave': 331,
 'away': 332,
 'store.that': 333,
 'happened': 334,
 'cause': 335,
 'not': 336,
 'beatable.did': 337,
 'give': 338,
 'any': 339,
 'clues': 340,
 'coordinates': 341,
 'anything': 342,
 'saw': 343,
 'few': 344,
 'back.i': 345,
 'had': 346,
 'vision': 347,
 'wan': 348,
 'believe': 349,
 'it.thought': 350,
 'dreaming.tony': 351,
 'focus.and': 352,
 'needed': 353,
 'you.as': 354,
 'past': 355,
 'tense.that': 356,
 'trumps': 357,
 'too': 358,
 'late': 359,
 'buddy.sorry.you': 360,
 'shave.and': 361,
 'remember': 362,
 'telling': 363,
 'youse': 364,
 'tony': 365,
 'alive': 366,
 'otherwise': 367,
 'suit': 368,
 'armor': 369,
 'world.remember': 370,
 'whether': 371,
 'impacted': 372,
 'our': 373,
 'precious': 374,
 'freedoms': 375,
 'not.that': 376,
 'needed.well': 377,
 'work': 378,
 'lose.you': 379,
 'together': 380,
 'guess': 381,
 'cap': 382,
 'lost.and': 383,
 'there.but': 384,
 'right': 385,
 'best': 386,
 'after': 387,
 'fact': 388,
 'avengers': 389,
 'pre': 390,
 'vengers': 391,
 'made': 392,
 'point': 393,
 'sit': 394,
 'here': 395,
 'she': 396,
 'great': 397,
 'by': 398,
 'sick': 399,
 'down.we': 400,
 'new': 401,
 'blood.bunch': 402,
 'tired': 403,
 'old': 404,
 'mules': 405,
 'nothing': 406,
 'cap.i': 407,
 'strategies': 408,
 'options.zero': 409,
 'zip': 410,
 'nada.no': 411,
 'trust': 412,
 'liar.here': 413,
 'this.you': 414,
 'put': 415,
 'hide': 416,
 'fine.let': 417,
 'me': 418,
 'bruce': 419,
 'sedative.he': 420,
 'day.you': 421,
 'care': 422,
 'bring': 423,
 'xorrian': 424,
 'elixir': 425,
 'come': 426,
 'back.where': 427,
 'kill': 428,
 'thanos.hey.you': 429,
 'usually': 430,
 'as': 431,
 'team': 432,
 'between': 433,
 'morale': 434,
 'fragile.we': 435,
 'realize': 436,
 'territory': 437,
 'too.you': 438,
 'people': 439,
 'might.do': 440,
 'bother.i': 441,
 'tell': 442,
 'is.thanos': 443,
 'spent': 444,
 'long': 445,
 'time': 446,
 'perfect': 447,
 'me.and': 448,
 'worked': 449,
 'talked': 450,
 'his': 451,
 'plan.even': 452,
 'disassembled': 453,
 'wanted': 454,
 'him.i': 455,
 'ask': 456,
 'once': 457,
 'plan': 458,
 'complete': 459,
 'answer': 460,
 'same.to': 461,
 'garden.that': 462,
 'cute': 463,
 'has': 464,
 'retirement': 465,
 'plan.so': 466,
 'snapped': 467,
 'fingers': 468,
 'earth': 469,
 'became': 470,
 'ground': 471,
 'zero': 472,
 'power': 473,
 'surge': 474,
 'ridiculously': 475,
 'cosmic': 476,
 'proportions.no': 477,
 'seen': 478,
 'it.until': 479,
 'two': 480,
 'ago': 481,
 'planet.thanos': 482,
 'there.he': 483,
 'used': 484,
 'stones': 485,
 'again.hey': 486,
 'hey.we': 487,
 'shorthanded': 488,
 'look': 489,
 'so': 490,
 'em.use': 491,
 'them': 492,
 'everyone': 493,
 'back.just': 494,
 'that.even': 495,
 'small': 496,
 'undo': 497,
 'owe': 498,
 'room': 499,
 'try.if': 500,
 'end': 501,
 'differently': 502,
 'than': 503,
 'before': 504,
 'because': 505,
 'me.hey': 506,
 'girl': 507,
 'everybody': 508,
 'superhero': 509,
 'life.and': 510,
 'mind': 511,
 'asking': 512,
 'hell': 513,
 'other': 514,
 'planets': 515,
 'universe.and': 516,
 'unfortunately': 517,
 'they': 518,
 'guys.i': 519,
 'one.let': 520,
 'son': 521,
 'bitch.okay.who': 522,
 'why': 523,
 'ship.approaching': 524,
 'jump': 525,
 'one.i': 526,
 'head': 527,
 'recon.this': 528,
 'steve.i': 529,
 "doesn't.no": 530,
 'ships': 531,
 'armies.no': 532,
 'defenses': 533,
 'kind.it': 534,
 'him.and': 535,
 'enough.oh': 536,
 'no.where': 537,
 'question.the': 538,
 'universe': 539,
 'required': 540,
 'correction.after': 541,
 'served': 542,
 'purpose': 543,
 'beyond': 544,
 'temptation.you': 545,
 'murdered': 546,
 'trillions': 547,
 'grateful.where': 548,
 'gone.reduced': 549,
 'atoms.you': 550,
 'destroy': 551,
 'stones.it': 552,
 'nearly': 553,
 'killed': 554,
 'me.but': 555,
 'done.it': 556,
 'be.i': 557,
 'am': 558,
 'inevitable.we': 559,
 'tear': 560,
 'place': 561,
 'apart': 562,
 'lying': 563,
 'father': 564,
 'many': 565,
 'things.a': 566,
 'liar': 567,
 'them.thank': 568,
 'daughter.perhaps': 569,
 'treated': 570,
 'harshly.what': 571,
 'went': 572,
 'head.so': 573,
 'date': 574,
 'day.it': 575,
 'first': 576,
 'five': 577,
 'years.you': 578,
 'sitting': 579,
 'at': 580,
 'dinner.i': 581,
 'talk': 582,
 'about.what': 583,
 'same': 584,
 'crap': 585,
 'things': 586,
 'changed.my': 587,
 'job.how': 588,
 'much': 589,
 'mets.and': 590,
 'quiet': 591,
 'cried': 592,
 'serving': 593,
 'salads.what': 594,
 'dessert.but': 595,
 'seeing': 596,
 'again': 597,
 'great.you': 598,
 'hardest': 599,
 'part': 600,
 'took': 601,
 'jump.you': 602,
 'down.and': 603,
 'those': 604,
 'brave': 605,
 'baby': 606,
 'steps': 607,
 'become': 608,
 'whole': 609,
 'purpose.i': 610,
 'ice': 611,
 '45': 612,
 'met': 613,
 'life.woke': 614,
 '70': 615,
 'later.you': 616,
 'on.': 617,
 'on.the': 618,
 'world': 619,
 'hands.it': 620,
 'left': 621,
 'us': 622,
 'guys.and': 623,
 'something': 624,
 'it.otherwise': 625,
 'us.what': 626,
 'kid': 627,
 'no.no.excuse': 628,
 'sorry.cassie': 629,
 'no.no': 630,
 'no.please': 631,
 'cassie.what': 632,
 'cassie': 633,
 'dad': 634,
 'big': 635,
 'boarded': 636,
 'highly': 637,
 'suspect': 638,
 'warship': 639,
 'danvers': 640,
 'pinged.it': 641,
 'an': 642,
 'infectious': 643,
 'garbage': 644,
 'scow.so': 645,
 'tip.well': 646,
 'closer.yeah': 647,
 'smell': 648,
 'garbage.you': 649,
 'reading': 650,
 'tremors': 651,
 'twas': 652,
 'mild': 653,
 'subduction': 654,
 'under': 655,
 'african': 656,
 'plate.do': 657,
 'visual': 658,
 'handling': 659,
 'nat.it': 660,
 'earthquake': 661,
 'ocean.we': 662,
 'handle': 663,
 'it.carol': 664,
 'next': 665,
 'month': 666,
 'likely': 667,
 'another': 668,
 'haircut': 669,
 'listen': 670,
 'fur': 671,
 'face.i': 672,
 'covering': 673,
 'territory.the': 674,
 'happening': 675,
 'everywhere.on': 676,
 'thousands': 677,
 'planets.all': 678,
 'point.so': 679,
 'might': 680,
 'time.all': 681,
 'channel': 682,
 'active.so': 683,
 'goes': 684,
 'sideways': 685,
 'anyone': 686,
 'making': 687,
 'trouble': 688,
 'comes': 689,
 'through': 690,
 'me.okay.all': 691,
 'right.good': 692,
 'luck.where': 693,
 'mexico.the': 694,
 'federales': 695,
 'found': 696,
 'full': 697,
 'bodies.looks': 698,
 'bunch': 699,
 'cartel': 700,
 'never': 701,
 'their': 702,
 'guns': 703,
 'off.it': 704,
 'rival': 705,
 'gang.except': 706,
 "isn't.it": 707,
 'definitely': 708,
 'barton.what': 709,
 'done': 710,
 'doing': 711,
 'scene': 712,
 'does': 713,
 'him.will': 714,
 'nat': 715,
 'okay.you': 716,
 'offer': 717,
 'cook': 718,
 'dinner': 719,
 'seem': 720,
 'pretty': 721,
 'miserable': 722,
 'already.you': 723,
 'laundry': 724,
 'friend.clearly': 725,
 'friend': 726,
 'fine.you': 727,
 'pod': 728,
 'whales': 729,
 'over': 730,
 'bridge': 731,
 'hudson': 732,
 'fewer': 733,
 'cleaner': 734,
 'water.you': 735,
 'bright': 736,
 'side': 737,
 'hit': 738,
 'peanut': 739,
 'butter': 740,
 'sandwich.sorry.force': 741,
 'habit.you': 742,
 'keep': 743,
 'grow.some': 744,
 'do.but': 745,
 'us.if': 746,
 'maybe': 747,
 'done.i': 748,
 'nothing.and': 749,
 'this.this': 750,
 'job.this': 751,
 'family.and': 752,
 'it.and': 753,
 'though': 754,
 'gone': 755,
 'better.i': 756,
 'think': 757,
 'life.you': 758,
 'first.hi': 759,
 'hi': 760,
 'home': 761,
 'scott': 762,
 'lang.we': 763,
 'airport': 764,
 'germany': 765,
 'guy': 766,
 'mask': 767,
 'recognize': 768,
 'message': 769,
 'ant': 770,
 'man': 771,
 'front': 772,
 'gate': 773,
 'guys.scott.are': 774,
 'yeah.have': 775,
 'either': 776,
 'studied': 777,
 'quantum': 778,
 'physics': 779,
 'only': 780,
 'make': 781,
 'conversation.all': 782,
 'called': 783,
 'realm.the': 784,
 'realm': 785,
 'own': 786,
 'microscopic': 787,
 'universe.to': 788,
 'incredibly': 789,
 'small.hope': 790,
 'supposed': 791,
 'out.and': 792,
 'stuck': 793,
 'there.i': 794,
 'sorry': 795,
 'must': 796,
 'very': 797,
 'years.yeah': 798,
 'it.it': 799,
 "wasn't.for": 800,
 'hours.see': 801,
 'rules': 802,
 'here.everything': 803,
 'unpredictable.is': 804,
 'anybody': 805,
 'sandwich': 806,
 'starving.scott.what': 807,
 'talking': 808,
 'saying': 809,
 'works': 810,
 'problem': 811,
 'navigate': 812,
 'it.but': 813,
 'ca': 814,
 'thinking': 815,
 'somehow': 816,
 'control': 817,
 'chaos': 818,
 'enter': 819,
 'certain': 820,
 'exit': 821,
 'wait.are': 822,
 'machine': 823,
 'machine.this': 824,
 'machine.i': 825,
 'crazy': 826,
 'crazy.but': 827,
 'some': 828,
 'scott.i': 829,
 'emails': 830,
 'raccoon': 831,
 'sounds': 832,
 'anymore.so': 833,
 'chow': 834,
 'maguna.morgan': 835,
 'h.': 836,
 'stark': 837,
 'lunch': 838,
 'define': 839,
 'disintegrated': 840,
 'wearing': 841,
 'special': 842,
 'anniversary': 843,
 'gift': 844,
 'mom.there': 845,
 'handful': 846,
 'crickets': 847,
 'bed': 848,
 'lettuce': 849,
 'want.how': 850,
 'garage': 851,
 'looking': 852,
 'no.i': 853,
 'though.you': 854,
 'huh': 855,
 'daddy.it': 856,
 'mom': 857,
 'wears': 858,
 'buy': 859,
 'her.so': 860,
 'like.tony': 861,
 'everything': 862,
 'impossible': 863,
 'fluctuation': 864,
 'messes': 865,
 'planck': 866,
 'scale': 867,
 'which': 868,
 'triggers': 869,
 'deutsch': 870,
 'proposition': 871,
 'agree': 872,
 'thank': 873,
 'you.in': 874,
 'layman': 875,
 'terms': 876,
 'means': 877,
 'no.you': 878,
 'accidentally': 879,
 'survived.it': 880,
 'billion': 881,
 'fluke.and': 882,
 'call': 883,
 'heist': 884,
 'laughable': 885,
 'pipe': 886,
 'dream.the': 887,
 'them.we': 888,
 'snap': 889,
 'back.or': 890,
 'screw': 891,
 'worse': 892,
 'already': 893,
 'would.': 894,
 'sometimes': 895,
 'giddy': 896,
 'optimism.however': 897,
 'high': 898,
 'hopes': 899,
 'wo': 900,
 'help': 901,
 'logical': 902,
 'tangible': 903,
 'safely': 904,
 'execute': 905,
 'heist.i': 906,
 'most': 907,
 'outcome': 908,
 'collective': 909,
 'demise.not': 910,
 'strictly': 911,
 'follow': 912,
 'travel.all': 913,
 'selves': 914,
 'betting': 915,
 'sporting': 916,
 'events.i': 917,
 'scott.are': 918,
 'seriously': 919,
 'save': 920,
 'based': 921,
 'future': 922,
 'no.good': 923,
 'worried': 924,
 'horseshit.that': 925,
 'works.tony.we': 926,
 'stand.we': 927,
 'stand': 928,
 'yet': 929,
 'are.i': 930,
 'line.you': 931,
 'wife': 932,
 'daughter.but': 933,
 'someone': 934,
 'important': 935,
 'me.a': 936,
 'lotta': 937,
 'did.and': 938,
 'her': 939,
 'even.i': 940,
 "can't.mommy": 941,
 'you.good': 942,
 'saved.i': 943,
 'wish': 944,
 'else': 945,
 'else.i': 946,
 'happy': 947,
 'table': 948,
 'set': 949,
 'six': 950,
 'tony.i': 951,
 'am.but': 952,
 'chance.i': 953,
 'cap.ca': 954,
 'roll': 955,
 'dice': 956,
 'it.if': 957,
 'shop': 958,
 'stay': 959,
 'lunch.well': 960,
 'scared.he': 961,
 'wrong.yeah': 962,
 'brain.bigger': 963,
 'eating': 964,
 'that.have': 965,
 'eggs.i': 966,
 'confused.these': 967,
 'confusing': 968,
 'times.right': 969,
 'meant.nah': 970,
 'kidding': 971,
 'crazy.i': 972,
 'shirts': 973,
 'now.yeah': 974,
 'asses': 975,
 'beat.except': 976,
 'twice.first': 977,
 'hulk': 978,
 'banner': 979,
 'lost.no': 980,
 'blamed': 981,
 'bruce.i': 982,
 'did.for': 983,
 'treating': 984,
 'kind': 985,
 'disease': 986,
 'rid': 987,
 'of.but': 988,
 'start': 989,
 'cure.eighteen': 990,
 'months': 991,
 'gamma': 992,
 'lab.i': 993,
 'brains': 994,
 'brawn': 995,
 'me.best': 996,
 'worlds': 997,
 'excuse': 998,
 'mr.': 999,
 ...}

In [110]:
len(vocab)

27153

In [111]:
data_frames = df.values.flatten().astype(str).tolist()

data_frames

["okay, hold on, don't shoot.",
 "you see where you're going? mm hmm.",
 'okay.',
 "now, let's worry about how you get there.",
 'gotta move your foot here.',
 'point your toe this way.',
 'your hips here.',
 'okay?',
 'can you see? yeah.',
 'are you sure? mm hmm.',
 'how about now? can you see now?',
 'no. how about now?',
 'all right.',
 'ready? three fingers.',
 'nice!',
 'nice throw, kiddo.',
 'here you go.',
 'hey, you guys want mayo? or mustard?',
 'or both?',
 'who puts mayo on a hot dog?',
 'probably your brothers.',
 'two mustard, please! thanks, mama.',
 'got it!',
 'nate, mayo or mustard?',
 'how about ketchup?',
 'or ketchup. i got ketchup, too.',
 'mind your elbow.',
 'good job, hawk eye.',
 'go get your arrow.',
 'hey, guys!',
 "enough practice. soup's on!",
 'all right.',
 "we're coming. we're hungry.",
 "lila, let's go.",
 'lila?',
 'honey?',
 'hey, babe?',
 'babe?',
 'babe?',
 'boys!',
 'boys!',
 'laura!',
 "you don't need to do that.",
 "because you're just holding the position.",
 'oh, yeah.',
 'that was close.',
 "that's a goal. we are now one apiece.",
 'i would like to try again.',
 "we're tied up. feel the tension?",
 "it's fun.",
 'that was terrible. now you have a chance to win.',
 "and you've won.",
 'congratulations.',
 'fair game.',
 'good sport.',
 'you have fun?',
 'it was fun.',
 'this thing on?',
 'hey, miss potts. pep.',
 'if you find this recording...',
 "don't post it on social media.",
 "it's gonna be a real tearjerker.",
 "i don't know if you're ever gonna see these.",
 "i don't even know if you're still...",
 'oh, god, i hope so.',
 "today's day 21.",
 'no, 22.',
 "you know, if it wasn't for the existential terror...",
 "of staring into the literal void of space, i'd say i'm feeling a little better today.",
 "infection's run its course, thanks to the blue meanie back there.",
 "you'd love her.",
 'very practical.',
 'only a tiny bit sadistic.',
 'so, the fuel cells were cracked during battle...',
 'and we figured out a way to reverse the ion charge...',
 'and bought ourselves about 48 hours of flight time.',
 "but it's now dead in the water.",
 'thousand light years from the nearest 7 eleven.',
 'oxygen will run out tomorrow morning...',
 "and that'll be it.",
 'pep, i know i said no more surprises...',
 'but i got to say i was really hoping to pull off one last one.',
 'but it looks like...',
 'well, you know what it looks like.',
 "don't feel bad about this.",
 'i mean, actually, if you grovel for a couple weeks...',
 'and then move on with enormous guilt...',
 'i should probably lie down for a minute. go rest my eyes.',
 'please know...',
 "when i drift off, it'll be like every night lately.",
 "i'm fine. totally fine.",
 'i dream about you.',
 "because it's always you.",
 "couldn't stop him.",
 'neither could i.',
 'hang on.',
 'i lost the kid.',
 'tony, we lost.',
 'is...?',
 'oh, good. oh, my god!',
 'oh, my god!',
 "it's okay.",
 "it's been 23 days since thanos came to earth.",
 'world governments are in pieces.',
 'the parts that are still working...',
 'are trying to take a census and it looks like he did...',
 'he did exactly what he said he was gonna do.',
 'thanos wiped out...',
 '50 of all living creatures.',
 'where is he now? where?',
 "we don't know.",
 'he just opened a portal and walked through.',
 "what's wrong with him?",
 "he's pissed.",
 'he thinks he failed.',
 'which, of course, he did...',
 "but there's a lot of that going around, ain't there?",
 'honestly, until this exact second i thought you were a build a bear.',
 'maybe i am.',
 "we've been hunting thanos for three weeks now.",
 'deep space scans...',
 'and satellites, and we got nothing.',
 'tony, you fought him.',
 'who told you that?',
 "i didn't fight him.",
 'no, he wiped my face with a planet...',
 'while the bleecker street magician gave away the store.',
 "that's what happened. there was no fight, cause he's not beatable.",
 'did he give you any clues, any coordinates, anything?',
 'i saw this coming a few years back.',
 "i had a vision. i didn't wanna believe it.",
 'thought i was dreaming.',
 "tony, i'm gonna need you to focus.",
 'and i needed you.',
 'as in, past tense.',
 "that trumps what you need. it's too late, buddy.",
 'sorry.',
 'you know what i need? i need a shave.',
 'and i believe i remember telling all youse...',
 'tony, tony!',
 'alive and otherwise, that what we needed was a suit of armor around the world.',
 'remember that? whether it impacted our precious freedoms or not.',
 "that's what we needed.",
 "well, that didn't work out, did it?",
 "i said we'd lose.",
 "you said, we'll do that together, too.",
 'and guess what, cap?',
 'we lost.',
 "and you weren't there.",
 "but that's what we do, right?",
 "our best work after the fact? we're the avengers.",
 "we're the avengers, not the pre vengers.",
 'okay. right?',
 'you made your point. just sit down, okay?',
 "okay. no, no, here's my point. you know what?",
 "she's great by the way. tony, you're sick. sit down.",
 "we need you. you're new blood.",
 'bunch of tired old mules. i got nothing for you, cap.',
 'i got no coordinates...',
 'no clues, no strategies, no options.',
 'zero. zip. nada.',
 'no trust, liar.',
 'here, take this.',
 'you find him, you put that on...',
 'you hide.',
 "tony! i'm fine.",
 'let me...',
 'bruce gave him a sedative.',
 "he's gonna probably be out for the rest of the day.",
 'you guys take care of him...',
 "and i'll bring him a xorrian elixir when i come back.",
 'where are you going?',
 'to kill thanos.',
 'hey.',
 'you know, we usually work as a team here...',
 "and, between you and i, morale's a little fragile.",
 'we realize up there is more your territory, but this is our fight, too.',
 'you even know where he is?',
 'i know people who might.',
 "don't bother.",
 'i can tell you where thanos is.',
 'thanos spent a long time trying to perfect me.',
 'and when he worked, he talked about his great plan.',
 'even disassembled, i wanted to please him.',
 "i'd ask...",
 'where would we go once his plan was complete?',
 'and his answer was always the same.',
 'to the garden.',
 "that's cute. thanos has a retirement plan.",
 'so, where is he?',
 'when thanos snapped his fingers...',
 'earth became ground zero for a power surge of ridiculously cosmic proportions.',
 "no one's ever seen anything like it.",
 'until two days ago...',
 'on this planet.',
 'thanos is there.',
 'he used the stones again.',
 'hey, hey, hey.',
 "we'd be going in shorthanded, you know?",
 "look, he's still got the stones, so...",
 "so, let's get em.",
 'use them to bring everyone back.',
 'just like that?',
 'yeah. just like that.',
 "even if there's a small chance that we can undo this...",
 "i mean, we owe it to everyone who's not in this room to try.",
 "if we do this, how do we know it's gonna end any differently than it did before?",
 "because before you didn't have me.",
 'hey, new girl?',
 'everybody in this room is about that superhero life.',
 "and if you don't mind my asking, where the hell have you been all this time?",
 'there are a lot of other planets in the universe.',
 "and unfortunately, they didn't have you guys.",
 'i like this one.',
 "let's go get this son of a bitch.",
 'okay.',
 "who here hasn't been to space?",
 'why?',
 'you better not throw up on my ship.',
 'approaching jump in three...',
 'two, one.',
 "i'll head down for recon.",
 'this is gonna work, steve.',
 'i know it will.',
 "cause i don't know what i'm gonna do if it doesn't.",
 'no satellites. no ships. no armies.',
 'no ground defenses of any kind.',
 "it's just him.",
 "and that's enough.",
 'oh, no.',
 'where are they?',
 'answer the question.',
 'the universe required correction.',
 'after that, the stones served no purpose...',
 'beyond temptation.',
 'you murdered trillions!',
 'you should be grateful.',
 'where are the stones?',
 'gone.',
 'reduced to atoms.',
 'you used them two days ago!',
 'i used the stones to destroy the stones.',
 'it nearly killed me.',
 'but the work is done.',
 'it always will be.',
 'i am inevitable.',
 'we have to tear this place apart. he has to be lying!',
 'my father is many things.',
 'a liar is not one of them.',
 'thank you, daughter.',
 'perhaps i treated you too harshly.',
 'what?',
 'what did you do?',
 'i went for the head.',
 'so...',
 'i went on a date the other day.',
 "it's the first time in five years.",
 "you know? i'm sitting there at dinner.",
 "i didn't even know what to talk about.",
 'what did you talk about?',
 'same old crap. you know, how things have changed.',
 'my job, his job.',
 'how much we miss the mets.',
 'and then things got quiet...',
 'then he cried as they were serving the salads.',
 'what about you?',
 'i cried just before dessert.',
 "but i'm seeing him again tomorrow, so...",
 "that's great.",
 'you did the hardest part. you took the jump.',
 "you didn't know where you were gonna come down.",
 "and that's it. that's those little brave baby steps we got to take...",
 'to try and become whole again, try and find purpose.',
 'i went in the ice in 45, right after i met the love of my life.',
 'woke up 70 years later.',
 'you got to move on.',
 'gotta move on.',
 'the world is in our hands.',
 "it's left to us, guys.",
 'and we got to do something with it.',
 'otherwise...',
 "thanos should've killed all of us.",
 'what the hell?',
 'hope?',
 'kid!',
 'hey, kid!',
 'what the hell happened here?',
 'oh, my god!',
 'oh, please!',
 'please, please!',
 'no, no, no. no.',
 'no.',
 'excuse me. sorry.',
 'cassie, no.',
 'no, no, no.',
 'no, no.',
 'please, please, please. no, cassie.',
 'what?',
 'cassie?',
 'dad?',
 "you're so big!",
 'yeah. we boarded that highly suspect warship danvers pinged.',
 'it was an infectious garbage scow.',
 'so, thanks for the hot tip.',
 'well, you were closer.',
 'yeah. and now we smell like garbage.',
 'you get a reading on those tremors?',
 'twas a mild subduction under the african plate.',
 'do we have a visual? how are we handling it?',
 'nat.',
 "it's an earthquake under the ocean.",
 'we handle it by not handling it.',
 'carol, are we seeing you here next month?',
 'not likely. what? you gonna get another haircut?',
 'listen, fur face.',
 "i'm covering a lot of territory.",
 'the things that are happening on earth are happening everywhere.',
 'on thousands of planets.',
 "all right, all right. that's a good point. that's a good point.",
 'so, you might not see me for a long time.',
 'all right. well...',
 "this channel's always active.",
 'so, if anything goes sideways...',
 "anyone's making trouble where they shouldn't...",
 'comes through me.',
 'okay.',
 'all right.',
 'good luck.',
 'where are you?',
 'mexico.',
 'the federales found a room full of bodies.',
 'looks like a bunch of cartel guys...',
 'never even had a chance to get their guns off.',
 "it's probably a rival gang.",
 "except it isn't.",
 "it's definitely barton.",
 "what he's done here...",
 "what he's been doing for the last few years...",
 'i mean, the scene that he left...',
 "i got to tell you, there's a part of me that doesn't even wanna find him.",
 "will you find out where he's going next?",
 'nat?',
 'please?',
 'okay.',
 "you know, i'd offer to cook you dinner...",
 'but you seem pretty miserable already.',
 'you here to do your laundry?',
 'and to see a friend.',
 'clearly, your friend is fine.',
 'you know, i saw a pod of whales when i was coming over the bridge.',
 "in the hudson? there's fewer ships...",
 'cleaner water.',
 "you know, if you're about to tell me to look on the bright side...",
 "i'm about to hit you in the head with a peanut butter sandwich.",
 'sorry.',
 'force of habit.',
 'you know, i keep telling everybody they should move on...',
 'and grow.',
 'some do.',
 'but not us.',
 'if i move on, who does this?',
 "maybe it doesn't need to be done.",
 'i used to have nothing.',
 'and then i got this.',
 'this job.',
 'this family.',
 'and i was better because of it.',
 "and even though they're gone...",
 "i'm still trying to be better.",
 'i think we both need to get a life.',
 'you first.',
 'hi, hi! is anyone home?',
 'this is scott lang.',
 'we met a few years ago at the airport...',
 'in germany?',
 'i was the guy that got really big. i had a mask on.',
 "you wouldn't recognize me. is this an old message?",
 'ant man? i know you know that.',
 "it's the front gate. i really need to talk to you guys.",
 'scott.',
 'are you okay?',
 'yeah.',
 'have either of you guys ever studied quantum physics?',
 'only to make conversation.',
 'all right, so...',
 'five years ago, right before...',
 'thanos...',
 'i was in a place called the quantum realm.',
 'the quantum realm is like its own microscopic universe.',
 'to get in there, you have to be incredibly small.',
 "hope. she's my...",
 'she was my...',
 'she was supposed to pull me out.',
 'and then thanos happened...',
 'and i got stuck in there.',
 "i'm sorry, that must have been a very long five years.",
 "yeah, but that's just it.",
 "it wasn't.",
 'for me, it was five hours.',
 "see, the rules of the quantum realm aren't like they are up here.",
 'everything is unpredictable.',
 "is that anybody's sandwich?",
 "i'm starving.",
 'scott.',
 'what are you talking about?',
 'so...',
 "what i'm saying is...",
 'time works differently in the quantum realm.',
 "the only problem is right now we don't have a way to navigate it.",
 'but what if we did?',
 "i can't stop thinking about it. what if we could somehow control the chaos...",
 'and we could navigate it?',
 'what if there was a way...',
 'that we could enter the quantum realm at a certain point in time...',
 'but then exit the quantum realm at another point in time?',
 'like...',
 'like before thanos. wait.',
 'are you talking about a time machine?',
 'no. no, of course not. no, not a time machine.',
 'this is more like a...',
 'yeah. like a time machine.',
 "i know, it's crazy. it's crazy.",
 "but i can't stop thinking about it. there's got to be...",
 'some way...',
 "it's crazy. scott.",
 'i get emails from a raccoon...',
 'so nothing sounds crazy anymore.',
 'so, who do we talk to about this?',
 'chow time!',
 'maguna.',
 'morgan h. stark, you want some lunch?',
 'define lunch or be disintegrated. okay.',
 'you should not be wearing that, okay?',
 "that is part of a special anniversary gift i'm making for mom.",
 'there you go. you thinking about lunch?',
 'i can give you a handful of crickets on a bed of lettuce.',
 "no. that's what you want.",
 'how did you find this?',
 'garage. really?',
 'were you looking for it? no.',
 'i found it, though.',
 'you like going in the garage, huh?',
 'so does daddy.',
 "it's fine, actually. mom never wears anything i buy her.",
 "so, i'm gonna...",
 'no. we know what it sounds like.',
 "tony, after everything you've seen, is anything really impossible?",
 'quantum fluctuation messes with the planck scale...',
 'which then triggers the deutsch proposition. can we agree on that?',
 'thank you.',
 "in layman's terms, it means you're not coming home.",
 'i did. no.',
 'you accidentally survived.',
 "it's a billion to one cosmic fluke.",
 'and now you wanna pull a... what do you call it?',
 'a time heist?',
 "yeah, a time heist. of course. why didn't we think of this before?",
 "oh, because it's laughable. because it's a pipe dream.",
 'the stones are in the past. we could go back, we could get them.',
 'we can snap our own fingers. we can bring everybody back.',
 'or screw it up worse than he already has, right?',
 "i don't believe we would.",
 'gotta say it. i sometimes miss that giddy optimism.',
 "however, high hopes won't help...",
 "if there's no logical, tangible way for me to safely execute said time heist.",
 'i believe the most likely outcome will be our collective demise.',
 'not if we strictly follow the rules of time travel.',
 'all right? it means no talking to our past selves...',
 'no betting on sporting events.',
 "i'm gonna stop you right there, scott.",
 'are you seriously telling me that your plan to save the universe...',
 'is based on back to the future?',
 'is it? no.',
 'good. you had me worried there. cause that would be horseshit.',
 "that's not how quantum physics works.",
 'tony.',
 'we have to take a stand.',
 'we did stand. and yet, here we are.',
 'i know you got a lot on the line.',
 'you got a wife, a daughter.',
 'but i lost someone very important to me.',
 'a lotta people did.',
 'and now, now we have a chance to bring her back...',
 "to bring everyone back, and you're telling me that you won't even...",
 "that's right, scott. i won't even.",
 "i can't.",
 'mommy told me to come and save you.',
 "good job. i'm saved.",
 'i wish you were coming here to ask me something else. anything else.',
 "i'm honestly happy to see you guys, i just...",
 "oh, look, the table's set for six. tony.",
 'i get it.',
 "and i'm happy for you. i really am.",
 'but this is a second chance.',
 'i got my second chance right here, cap.',
 "can't roll the dice on it.",
 "if you don't talk shop, you can stay for lunch.",
 "well, he's scared.",
 "he's not wrong.",
 'yeah, but, i mean, what are we gonna do?',
 'we need him. what, are we gonna stop?',
 'no, i wanna do it right.',
 "we're gonna need a really big brain.",
 'bigger than his?',
 "come on, i feel like i'm the only one eating here. try some of that.",
 'have some eggs.',
 "i'm so confused.",
 'these are confusing times.',
 "right, no, no. that's not what i meant.",
 "nah, i get it. i'm kidding!",
 "i know, it's crazy.",
 "i'm wearing shirts now.",
 'yeah. what? how? why?',
 'five years ago, we got our asses beat.',
 'except it was worse for me...',
 'cause i lost twice.',
 'first, hulk lost, then banner lost...',
 'and then, we all lost.',
 'no one blamed you, bruce.',
 'i did.',
 "for years, i've been treating the hulk like he's some kind of disease...",
 'something to get rid of.',
 'but then, i start looking at him as the cure.',
 'eighteen months in the gamma lab.',
 'i put the brains and the brawn together...',
 'and now, look at me.',
 'best of both worlds.',
 'excuse me, mr. hulk? yes.',
 'can we get a photo?',
 '100 , little person.',
 'come on, step on up. do you mind?',
 'oh, yeah, yeah. thanks.',
 'say green.',
 'green. green.',
 'did you get that?',
 "that's a good one.",
 "did you want to grab one with me? i'm ant man.",
 "they're hulk fans. they don't know ant man.",
 'nobody does.',
 "no, he wants you to take a picture with him. i don't want a picture.",
 'stranger danger.',
 "yeah, look, he's even saying no, he doesn't.",
 "i get it. i don't want it, either. but come on. the kid...",
 "i don't want a picture with them.",
 "he's gonna feel bad. sorry.",
 "they're happy to do it. they said they'll do it.",
 "i don't want to do it. we can do it.",
 'no, you feel bad. take the goddamn phone.',
 'okay.',
 'thank you, mr. hulk. no, it was great, kids. thank you very much.',
 'hulk out!',
 'bruce.',
 'dab.',
 'bruce. listen to your mom.',
 'she knows better.',
 'about what we were saying.',
 'right.',
 'the whole time travel do over?',
 "guys, it's outside of my area of expertise.",
 'well, you pulled this off.',
 'i remember a time when that seemed pretty impossible, too.',
 "i've got a mild inspiration. i'd like to see if it checks out.",
 "so, i'd like to run one last sim before we pack it in for the night.",
 'this time, in the shape of a mobius strip, inverted, please.',
 'processing.',
 'right, give me the eigenvalue of that particle...',
 'factoring in spectral decomp.',
 "that'll take a second. just a moment.",
 "and don't worry if it doesn't pan out. i'm just kinda...",
 'model rendered.',
 'shit!',
 'shit!',
 'what are you doing up, little miss?',
 "shit. nope. we don't say that.",
 'only mommy says that word.',
 'she coined it. it belongs to her.',
 'why are you up?',
 "cause i've got some important shit going on here!",
 'why do you think?',
 'no, i got something on my mind. i got something on my mind.',

In [112]:
def text_to_indices(sentence, vocab):

  numerical_sentence = []

  for token in sentence:
    if token in vocab:
      numerical_sentence.append(vocab[token])
    else:
      numerical_sentence.append(vocab['<unk>'])

  return numerical_sentence

In [113]:
input_numerical_sentences = []

for sentence in data_frames:
    sentence = f"start_token {sentence} end_token"
    # print(sentence)
    input_numerical_sentences.append(text_to_indices(word_tokenize(sentence.lower()), vocab))

In [114]:
input_numerical_sentences

[[1, 3, 4, 5, 6, 4, 7, 8, 9, 10, 2],
 [1, 11, 12, 13, 11, 14, 15, 16, 17, 2659, 10, 2],
 [1, 3, 10, 2],
 [1, 42, 4, 19, 20, 21, 22, 23, 11, 24, 303, 10, 2],
 [1, 26, 27, 28, 29, 30, 395, 10, 2],
 [1, 393, 29, 32, 33, 190, 10, 2],
 [1, 29, 35, 395, 10, 2],
 [1, 3, 16, 2],
 [1, 37, 11, 12, 16, 38, 10, 2],
 [1, 39, 11, 40, 16, 17, 2659, 10, 2],
 [1, 23, 22, 42, 16, 37, 11, 12, 42, 16, 2],
 [1, 43, 10, 23, 22, 42, 16, 2],
 [1, 44, 385, 10, 2],
 [1, 1406, 16, 46, 468, 10, 2],
 [1, 49, 48, 2],
 [1, 49, 50, 4, 0, 10, 2],
 [1, 395, 11, 244, 10, 2],
 [1, 88, 4, 11, 53, 54, 55, 16, 56, 57, 16, 2],
 [1, 56, 58, 16, 2],
 [1, 59, 60, 55, 6, 61, 62, 63, 16, 2],
 [1, 64, 29, 9656, 10, 2],
 [1, 480, 57, 4, 66, 48, 67, 4, 19718, 10, 2],
 [1, 26, 69, 48, 2],
 [1, 70, 4, 55, 56, 57, 16, 2],
 [1, 23, 22, 71, 16, 2],
 [1, 56, 71, 10, 72, 26, 71, 4, 358, 10, 2],
 [1, 511, 29, 0, 10, 2],
 [1, 268, 75, 4, 76, 1596, 10, 2],
 [1, 244, 24, 29, 7967, 10, 2],
 [1, 88, 4, 53, 48, 2],
 [1, 79, 80, 10, 81, 20, 6, 48, 2],
 [1, 44, 385, 10, 2],
 [1, 84, 14, 83, 10, 84, 14, 2660, 10, 2],
 [1, 1450, 4, 19, 20, 244, 10, 2],
 [1, 1450, 16, 2],
 [1, 87, 16, 2],
 [1, 88, 4, 89, 16, 2],
 [1, 89, 16, 2],
 [1, 89, 16, 2],
 [1, 90, 48, 2],
 [1, 90, 48, 2],
 [1, 91, 48, 2],
 [1, 11, 7, 8, 92, 93, 7, 212, 10, 2],
 [1, 505, 11, 14, 95, 96, 97, 6645, 10, 2],
 [1, 145, 4, 38, 10, 2],
 [1, 212, 100, 4595, 10, 2],
 [1, 212, 20, 61, 102, 10, 84, 39, 42, 103, 24847, 10, 2],
 [1, 72, 105, 106, 93, 107, 597, 10, 2],
 [1, 84, 14, 109, 110, 10, 111, 97, 112, 16, 2],
 [1, 69, 20, 122, 10, 2],
 [1, 212, 100, 114, 10, 42, 11, 115, 61, 116, 93, 2577, 10, 2],
 [1, 187, 11, 118, 2613, 10, 2],
 [1, 5441, 10, 2],
 [1, 2703, 1291, 10, 2],
 [1, 268, 9893, 10, 2],
 [1, 11, 115, 122, 16, 2],
 [1, 69, 100, 122, 10, 2],
 [1, 33, 124, 6, 16, 2],
 [1, 88, 4, 125, 126, 10, 2161, 10, 2],
 [1, 140, 11, 128, 33, 129, 130, 2],
 [1, 7, 8, 131, 69, 6, 132, 0, 10, 2],
 [1, 69, 20, 134, 135, 136, 61, 137, 0, 10, 2],
 [1, 72, 7, 8, 139, 140, 11, 14, 141, 134, 135, 12, 1209, 10, 2],
 [1, 72, 7, 8, 143, 139, 140, 11, 14, 144, 130, 2],
 [1, 145, 4, 146, 4, 72, 147, 490, 10, 2],
 [1, 1656, 20, 149, 0, 2],
 [1, 43, 4, 0, 2],
 [1, 11, 139, 4, 140, 69, 100, 8, 152, 97, 153, 154, 130, 2],
 [1,
  155,
  156,
  157,
  97,
  158,
  159,
  155,
  160,
  4,
  72,
  161,
  162,
  72,
  163,
  164,
  61,
  165,
  166,
  1656,
  10,
  2],
 [1, 25893, 20, 168, 169, 170, 4, 67, 93, 97, 171, 172, 173, 303, 10, 2],
 [1, 11, 161, 175, 939, 10, 2],
 [1, 797, 25045, 10, 2],
 [1, 780, 61, 178, 179, 0, 10, 2],
 [1, 490, 4, 97, 181, 182, 183, 184, 185, 186, 130, 2],
 [1, 187, 84, 188, 189, 61, 190, 93, 191, 97, 192, 193, 130, 2],
 [1, 187, 194, 195, 22, 196, 197, 155, 198, 446, 10, 2],
 [1, 218, 69, 20, 42, 200, 201, 97, 4152, 10, 2],
 [1, 2678, 203, 204, 205, 97, 206, 207, 9758, 10, 2],
 [1, 27011, 209, 168, 189, 210, 211, 130, 2],
 [1, 187, 212, 213, 136, 69, 10, 2],
 [1, 2161, 4, 72, 139, 72, 215, 43, 216, 217, 130, 2],
 [1,
  218,
  72,
  26,
  93,
  162,
  72,
  100,
  219,
  220,
  93,
  221,
  222,
  103,
  223,
  103,
  10,
  2],
 [1, 218, 69, 225, 106, 130, 2],
 [1, 226, 4, 11, 139, 227, 69, 225, 106, 10, 2],
 [1, 7, 8, 111, 229, 22, 33, 10, 2],
 [1, 72, 231, 4, 232, 4, 140, 11, 233, 152, 61, 234, 235, 130, 2],
 [1, 187, 236, 28, 6, 237, 238, 239, 130, 2],
 [1, 72, 240, 64, 241, 242, 152, 61, 243, 10, 244, 245, 246, 1835, 10, 2],
 [1, 66, 139, 130, 2],
 [1, 248, 72, 249, 222, 4, 69, 213, 136, 106, 250, 251, 0, 10, 2],
 [1, 72, 163, 253, 10, 254, 253, 10, 2],
 [1, 72, 256, 22, 11, 10, 2],
 [1, 505, 69, 20, 258, 11, 10, 2],
 [1, 262, 8, 260, 299, 10, 2],
 [1, 3705, 262, 3873, 2],
 [1, 1314, 6, 10, 2],
 [1, 72, 265, 97, 627, 10, 2],
 [1, 365, 4, 84, 265, 10, 2],
 [1, 292, 130, 16, 2],
 [1, 145, 4, 268, 10, 145, 4, 246, 146, 48, 2],
 [1, 145, 4, 246, 146, 48, 2],
 [1, 69, 20, 3, 10, 2],
 [1, 69, 20, 270, 271, 272, 273, 274, 275, 93, 469, 10, 2],
 [1, 619, 277, 39, 201, 17370, 10, 2],
 [1, 97, 279, 212, 39, 144, 280, 130, 2],
 [1, 39, 281, 93, 282, 61, 283, 187, 69, 225, 106, 284, 285, 130, 2],
 [1, 284, 285, 286, 227, 284, 215, 284, 100, 134, 135, 7, 10, 2],
 [1, 274, 288, 189, 130, 2],
 [1, 289, 155, 44, 290, 7380, 10, 2],
 [1, 13, 292, 284, 42, 16, 13, 16, 2],
 [1, 84, 7, 8, 139, 10, 2],
 [1, 284, 95, 294, 61, 295, 187, 296, 690, 10, 2],
 [1, 227, 20, 298, 237, 299, 16, 2],
 [1, 284, 20, 5251, 10, 2],
 [1, 284, 301, 284, 6047, 10, 2],
 [1, 868, 4, 155, 170, 4, 284, 285, 130, 2],
 [1, 218, 303, 20, 61, 304, 155, 212, 15, 305, 4, 306, 8, 303, 16, 2],
 [1, 307, 4, 308, 33, 309, 310, 72, 311, 11, 183, 61, 312, 61, 14721, 10, 2],
 [1, 747, 72, 558, 10, 2],
 [1, 84, 118, 270, 315, 274, 152, 46, 235, 42, 10, 2],
 [1, 3261, 160, 317, 130, 2],
 [1, 187, 318, 4, 187, 84, 26, 406, 10, 2],
 [1, 365, 4, 11, 320, 299, 10, 2],
 [1, 59, 322, 11, 212, 16, 2],
 [1, 72, 285, 8, 323, 299, 10, 2],
 [1, 43, 4, 284, 288, 246, 325, 237, 61, 326, 130, 2],
 [1, 327, 97, 328, 329, 330, 331, 332, 97, 15409, 10, 2],
 [1, 212, 20, 227, 334, 10, 303, 100, 43, 323, 4, 335, 284, 20, 336, 0, 10, 2],
 [1, 285, 284, 338, 11, 339, 340, 4, 339, 341, 4, 342, 16, 2],
 [1, 72, 343, 33, 83, 61, 344, 204, 173, 10, 2],
 [1, 72, 346, 61, 347, 10, 72, 285, 8, 348, 135, 349, 69, 10, 2],
 [1, 311, 72, 100, 0, 10, 2],
 [1, 365, 4, 72, 163, 134, 135, 92, 11, 93, 1845, 10, 2],
 [1, 187, 72, 353, 11, 10, 2],
 [1, 431, 201, 4, 355, 8771, 10, 2],
 [1, 212, 357, 227, 11, 92, 10, 69, 20, 358, 359, 4, 1796, 10, 2],
 [1, 795, 10, 2],
 [1, 11, 139, 227, 72, 92, 16, 72, 92, 61, 9904, 10, 2],
 [1, 187, 72, 349, 72, 362, 363, 44, 364, 130, 2],
 [1, 365, 4, 365, 48, 2],
 [1,
  366,
  187,
  367,
  4,
  212,
  227,
  84,
  353,
  100,
  61,
  368,
  155,
  369,
  305,
  97,
  619,
  10,
  2],
 [1, 362, 212, 16, 371, 69, 372, 373, 374, 375, 56, 336, 10, 2],
 [1, 212, 20, 227, 84, 353, 10, 2],
 [1, 226, 4, 212, 285, 8, 378, 189, 4, 285, 69, 16, 2],
 [1, 72, 215, 84, 161, 1141, 10, 2],
 [1, 11, 215, 4, 84, 213, 7, 212, 380, 4, 358, 10, 2],
 [1, 187, 381, 227, 4, 382, 16, 2],
 [1, 84, 265, 10, 2],
 [1, 187, 11, 183, 8, 303, 10, 2],
 [1, 218, 212, 20, 227, 84, 7, 4, 385, 16, 2],
 [1, 373, 386, 378, 387, 97, 388, 16, 84, 14, 97, 389, 10, 2],
 [1, 84, 14, 97, 389, 4, 336, 97, 390, 391, 10, 2],
 [1, 3, 10, 385, 16, 2],
 [1, 11, 392, 29, 393, 10, 95, 394, 242, 4, 3, 16, 2],
 [1, 3, 10, 43, 4, 43, 4, 395, 20, 246, 393, 10, 11, 139, 227, 16, 2],
 [1, 396, 20, 397, 398, 97, 190, 10, 365, 4, 11, 14, 399, 10, 394, 242, 10, 2],
 [1, 84, 92, 11, 10, 11, 14, 401, 3263, 10, 2],
 [1, 699, 155, 403, 404, 405, 10, 72, 26, 406, 152, 11, 4, 382, 10, 2],
 [1, 72, 26, 43, 341, 130, 2],
 [1, 43, 340, 4, 43, 408, 4, 43, 2125, 10, 2],
 [1, 472, 10, 410, 10, 0, 10, 2],
 [1, 43, 412, 4, 567, 10, 2],
 [1, 395, 4, 282, 33, 10, 2],
 [1, 11, 128, 299, 4, 11, 415, 212, 6, 130, 2],
 [1, 11, 416, 10, 2],
 [1, 365, 48, 72, 163, 253, 10, 2],
 [1, 19, 418, 130, 2],
 [1, 419, 331, 299, 61, 0, 10, 2],
 [1, 284, 20, 134, 135, 64, 136, 189, 152, 97, 245, 155, 97, 149, 10, 2],
 [1, 11, 53, 282, 422, 155, 299, 130, 2],
 [1, 187, 72, 213, 423, 299, 61, 424, 425, 248, 72, 426, 173, 10, 2],
 [1, 13, 39, 11, 15, 16, 2],
 [1, 93, 428, 274, 10, 2],
 [1, 88, 10, 2],
 [1, 11, 139, 4, 84, 430, 378, 431, 61, 432, 395, 130, 2],
 [1, 187, 4, 433, 11, 187, 72, 4, 434, 20, 61, 165, 0, 10, 2],
 [1,
  84,
  436,
  110,
  303,
  292,
  216,
  29,
  437,
  4,
  218,
  33,
  292,
  373,
  323,
  4,
  358,
  10,
  2],
 [1, 11, 143, 139, 13, 284, 292, 16, 2],
 [1, 72, 139, 439, 59, 680, 10, 2],
 [1, 7, 8, 12597, 10, 2],
 [1, 72, 37, 442, 11, 13, 274, 292, 10, 2],
 [1, 274, 444, 61, 445, 446, 281, 93, 447, 418, 10, 2],
 [1, 187, 248, 284, 449, 4, 284, 450, 22, 451, 397, 458, 10, 2],
 [1, 143, 453, 4, 72, 454, 93, 66, 299, 10, 2],
 [1, 72, 161, 456, 130, 2],
 [1, 13, 105, 84, 244, 457, 451, 458, 100, 459, 16, 2],
 [1, 187, 451, 460, 100, 258, 97, 584, 10, 2],
 [1, 93, 97, 2142, 10, 2],
 [1, 212, 20, 463, 10, 274, 464, 61, 465, 458, 10, 2],
 [1, 490, 4, 13, 292, 284, 16, 2],
 [1, 248, 274, 467, 451, 468, 130, 2],
 [1, 469, 470, 471, 472, 152, 61, 473, 474, 155, 475, 476, 0, 10, 2],
 [1, 43, 103, 20, 141, 478, 342, 106, 69, 10, 2],
 [1, 308, 480, 272, 481, 130, 2],
 [1, 6, 33, 326, 10, 2],
 [1, 274, 292, 303, 10, 2],
 [1, 284, 484, 97, 485, 597, 10, 2],
 [1, 88, 4, 88, 4, 88, 10, 2],
 [1, 84, 161, 136, 15, 201, 488, 4, 11, 139, 16, 2],
 [1, 489, 4, 284, 20, 144, 26, 97, 485, 4, 490, 130, 2],
 [1, 490, 4, 19, 20, 24, 2363, 10, 2],
 [1, 2131, 492, 93, 423, 493, 173, 10, 2],
 [1, 95, 106, 212, 16, 2],
 [1, 38, 10, 95, 106, 212, 10, 2],
 [1, 143, 140, 303, 20, 61, 496, 116, 212, 84, 37, 497, 33, 130, 2],
 [1,
  72,
  231,
  4,
  84,
  498,
  69,
  93,
  493,
  59,
  20,
  336,
  201,
  33,
  499,
  93,
  107,
  10,
  2],
 [1,
  140,
  84,
  7,
  33,
  4,
  23,
  7,
  84,
  139,
  69,
  20,
  134,
  135,
  501,
  339,
  502,
  503,
  69,
  285,
  504,
  16,
  2],
 [1, 505, 504, 11, 285, 8, 115, 418, 10, 2],
 [1, 88, 4, 401, 507, 16, 2],
 [1, 508, 201, 33, 499, 292, 22, 212, 509, 1514, 10, 2],
 [1,
  187,
  140,
  11,
  7,
  8,
  511,
  246,
  512,
  4,
  13,
  97,
  513,
  115,
  11,
  270,
  44,
  33,
  446,
  16,
  2],
 [1, 303, 39, 61, 304, 155, 514, 515, 201, 97, 539, 10, 2],
 [1, 187, 517, 4, 518, 285, 8, 115, 11, 53, 10, 2],
 [1, 72, 106, 33, 103, 10, 2],
 [1, 19, 20, 244, 24, 33, 521, 155, 61, 9751, 10, 2],
 [1, 3, 10, 2],
 [1, 59, 395, 464, 8, 270, 93, 160, 16, 2],
 [1, 523, 16, 2],
 [1, 11, 166, 336, 50, 110, 6, 246, 2688, 10, 2],
 [1, 1748, 525, 201, 46, 130, 2],
 [1, 480, 4, 103, 10, 2],
 [1, 72, 213, 527, 242, 152, 24414, 10, 2],
 [1, 33, 292, 134, 135, 378, 4, 2157, 10, 2],
 [1, 72, 139, 69, 209, 10, 2],
 [1, 335, 72, 7, 8, 139, 227, 72, 163, 134, 135, 7, 140, 69, 713, 8, 10, 2],
 [1, 43, 318, 10, 43, 531, 10, 43, 2816, 10, 2],
 [1, 43, 471, 533, 155, 339, 985, 10, 2],
 [1, 69, 20, 95, 299, 10, 2],
 [1, 187, 212, 20, 79, 10, 2],
 [1, 145, 4, 43, 10, 2],
 [1, 13, 39, 518, 16, 2],
 [1, 460, 97, 7132, 10, 2],
 [1, 97, 539, 540, 18073, 10, 2],
 [1, 387, 212, 4, 97, 485, 542, 43, 543, 130, 2],
 [1, 544, 0, 10, 2],
 [1, 11, 546, 547, 48, 2],
 [1, 11, 240, 136, 2514, 10, 2],
 [1, 13, 39, 97, 485, 16, 2],
 [1, 755, 10, 2],
 [1, 23623, 93, 16081, 10, 2],
 [1, 11, 484, 492, 480, 272, 481, 48, 2],
 [1, 72, 484, 97, 485, 93, 551, 97, 485, 10, 2],
 [1, 69, 553, 554, 418, 10, 2],
 [1, 218, 97, 378, 292, 710, 10, 2],
 [1, 69, 258, 209, 136, 10, 2],
 [1, 72, 558, 0, 10, 2],
 [1, 84, 115, 93, 560, 33, 561, 562, 10, 284, 464, 93, 136, 563, 48, 2],
 [1, 246, 564, 292, 565, 586, 10, 2],
 [1, 61, 567, 292, 336, 103, 155, 492, 10, 2],
 [1, 873, 11, 4, 2098, 10, 2],
 [1, 3445, 72, 570, 11, 358, 0, 10, 2],
 [1, 227, 16, 2],
 [1, 227, 285, 11, 7, 16, 2],
 [1, 72, 572, 152, 97, 527, 10, 2],
 [1, 490, 130, 2],
 [1, 72, 572, 6, 61, 574, 97, 514, 149, 10, 2],
 [1, 69, 20, 97, 576, 446, 201, 577, 204, 10, 2],
 [1, 11, 139, 16, 72, 163, 579, 303, 580, 719, 10, 2],
 [1, 72, 285, 8, 143, 139, 227, 93, 582, 22, 10, 2],
 [1, 227, 285, 11, 582, 22, 16, 2],
 [1, 584, 404, 585, 10, 11, 139, 4, 23, 586, 115, 1444, 10, 2],
 [1, 246, 75, 4, 451, 75, 10, 2],
 [1, 23, 589, 84, 125, 97, 0, 10, 2],
 [1, 187, 236, 586, 26, 591, 130, 2],
 [1, 236, 284, 592, 431, 518, 183, 593, 97, 0, 10, 2],
 [1, 227, 22, 11, 16, 2],
 [1, 72, 592, 95, 504, 22203, 10, 2],
 [1, 218, 72, 163, 596, 299, 597, 210, 4, 490, 130, 2],
 [1, 212, 20, 397, 10, 2],
 [1, 11, 285, 97, 599, 600, 10, 11, 601, 97, 525, 10, 2],
 [1, 11, 285, 8, 139, 13, 11, 183, 134, 135, 426, 242, 10, 2],
 [1,
  187,
  212,
  20,
  69,
  10,
  212,
  20,
  604,
  165,
  605,
  606,
  607,
  84,
  26,
  93,
  282,
  130,
  2],
 [1, 93, 107, 187, 608, 609, 597, 4, 107, 187, 128, 543, 10, 2],
 [1,
  72,
  572,
  201,
  97,
  611,
  201,
  612,
  4,
  385,
  387,
  72,
  613,
  97,
  175,
  155,
  246,
  1514,
  10,
  2],
 [1, 2550, 110, 615, 204, 5000, 10, 2],
 [1, 11, 26, 93, 28, 6, 10, 2],
 [1, 26, 27, 28, 6, 10, 2],
 [1, 97, 619, 292, 201, 373, 1881, 10, 2],
 [1, 69, 20, 621, 93, 622, 4, 53, 10, 2],
 [1, 187, 84, 26, 93, 7, 624, 237, 69, 10, 2],
 [1, 367, 130, 2],
 [1, 274, 240, 118, 554, 44, 155, 622, 10, 2],
 [1, 227, 97, 513, 16, 2],
 [1, 147, 16, 2],
 [1, 627, 48, 2],
 [1, 88, 4, 627, 48, 2],
 [1, 227, 97, 513, 334, 395, 16, 2],
 [1, 145, 4, 246, 146, 48, 2],
 [1, 145, 4, 66, 48, 2],
 [1, 66, 4, 66, 48, 2],
 [1, 43, 4, 43, 4, 43, 10, 43, 10, 2],
 [1, 43, 10, 2],
 [1, 998, 418, 10, 795, 10, 2],
 [1, 633, 4, 43, 10, 2],
 [1, 43, 4, 43, 4, 43, 10, 2],
 [1, 43, 4, 43, 10, 2],
 [1, 66, 4, 66, 4, 66, 10, 43, 4, 633, 10, 2],
 [1, 227, 16, 2],
 [1, 633, 16, 2],
 [1, 634, 16, 2],
 [1, 11, 14, 490, 635, 48, 2],
 [1, 38, 10, 84, 636, 212, 637, 638, 639, 640, 0, 10, 2],
 [1, 69, 100, 642, 643, 644, 0, 10, 2],
 [1, 490, 4, 67, 152, 97, 62, 5328, 10, 2],
 [1, 226, 4, 11, 183, 2780, 10, 2],
 [1, 38, 10, 187, 42, 84, 648, 106, 644, 10, 2],
 [1, 11, 24, 61, 650, 6, 604, 651, 16, 2],
 [1, 652, 61, 653, 654, 655, 97, 656, 23227, 10, 2],
 [1, 7, 84, 115, 61, 658, 16, 23, 39, 84, 659, 69, 16, 2],
 [1, 715, 10, 2],
 [1, 69, 20, 642, 661, 655, 97, 15733, 10, 2],
 [1, 84, 663, 69, 398, 336, 659, 69, 10, 2],
 [1, 11932, 4, 39, 84, 596, 11, 395, 665, 666, 16, 2],
 [1, 336, 667, 10, 227, 16, 11, 134, 135, 24, 668, 669, 16, 2],
 [1, 670, 4, 671, 325, 10, 2],
 [1, 72, 163, 673, 61, 304, 155, 437, 10, 2],
 [1, 97, 586, 212, 39, 675, 6, 469, 39, 675, 4582, 10, 2],
 [1, 6, 677, 155, 515, 10, 2],
 [1,
  44,
  385,
  4,
  44,
  385,
  10,
  212,
  20,
  61,
  268,
  393,
  10,
  212,
  20,
  61,
  268,
  393,
  10,
  2],
 [1, 490, 4, 11, 680, 336, 12, 418, 152, 61, 445, 446, 10, 2],
 [1, 44, 385, 10, 226, 130, 2],
 [1, 33, 682, 20, 258, 6739, 10, 2],
 [1, 490, 4, 140, 342, 684, 685, 130, 2],
 [1, 686, 20, 687, 688, 13, 518, 240, 8, 130, 2],
 [1, 689, 690, 418, 10, 2],
 [1, 3, 10, 2],
 [1, 44, 385, 10, 2],
 [1, 268, 1162, 10, 2],
 [1, 13, 39, 11, 16, 2],
 [1, 3129, 10, 2],
 [1, 97, 695, 696, 61, 499, 697, 155, 4501, 10, 2],
 [1, 225, 106, 61, 699, 155, 700, 53, 130, 2],
 [1, 701, 143, 346, 61, 116, 93, 24, 702, 703, 222, 10, 2],
 [1, 69, 20, 64, 61, 705, 14934, 10, 2],
 [1, 4292, 69, 292, 8, 10, 2],
 [1, 69, 20, 708, 2105, 10, 2],
 [1, 227, 284, 20, 710, 395, 130, 2],
 [1, 227, 284, 20, 270, 711, 152, 97, 223, 344, 204, 130, 2],
 [1, 72, 231, 4, 97, 712, 212, 284, 621, 130, 2],
 [1,
  72,
  26,
  93,
  442,
  11,
  4,
  303,
  20,
  61,
  600,
  155,
  418,
  212,
  713,
  8,
  143,
  348,
  135,
  128,
  299,
  10,
  2],
 [1, 209, 11, 128, 189, 13, 284, 20, 15, 665, 16, 2],
 [1, 715, 16, 2],
 [1, 66, 16, 2],
 [1, 3, 10, 2],
 [1, 11, 139, 4, 72, 161, 717, 93, 718, 11, 719, 130, 2],
 [1, 218, 11, 720, 721, 722, 893, 10, 2],
 [1, 11, 395, 93, 7, 29, 724, 16, 2],
 [1, 187, 93, 12, 61, 726, 10, 2],
 [1, 5765, 4, 29, 726, 292, 253, 10, 2],
 [1,
  11,
  139,
  4,
  72,
  343,
  61,
  728,
  155,
  729,
  248,
  72,
  100,
  83,
  730,
  97,
  731,
  10,
  2],
 [1, 201, 97, 732, 16, 303, 20, 733, 531, 130, 2],
 [1, 734, 4152, 10, 2],
 [1,
  11,
  139,
  4,
  140,
  11,
  14,
  22,
  93,
  442,
  418,
  93,
  489,
  6,
  97,
  736,
  737,
  130,
  2],
 [1, 72, 163, 22, 93, 738, 11, 201, 97, 527, 237, 61, 739, 740, 806, 10, 2],
 [1, 795, 10, 2],
 [1, 6528, 155, 17532, 10, 2],
 [1, 11, 139, 4, 72, 743, 363, 508, 518, 240, 28, 6, 130, 2],
 [1, 187, 1169, 10, 2],
 [1, 828, 7, 10, 2],
 [1, 218, 336, 622, 10, 2],
 [1, 140, 72, 28, 6, 4, 59, 713, 33, 16, 2],
 [1, 747, 69, 713, 8, 92, 93, 136, 710, 10, 2],
 [1, 72, 484, 93, 115, 406, 10, 2],
 [1, 187, 236, 72, 26, 33, 10, 2],
 [1, 33, 75, 10, 2],
 [1, 33, 1374, 10, 2],
 [1, 187, 72, 100, 166, 505, 155, 69, 10, 2],
 [1, 187, 143, 754, 518, 14, 755, 130, 2],
 [1, 72, 163, 144, 281, 93, 136, 166, 10, 2],
 [1, 72, 757, 84, 58, 92, 93, 24, 61, 1514, 10, 2],
 [1, 11, 576, 10, 2],
 [1, 760, 4, 760, 48, 292, 686, 761, 16, 2],
 [1, 33, 292, 762, 1186, 10, 2],
 [1, 84, 613, 61, 344, 204, 481, 580, 97, 764, 130, 2],
 [1, 201, 765, 16, 2],
 [1, 72, 100, 97, 766, 212, 26, 219, 635, 10, 72, 346, 61, 767, 6, 10, 2],
 [1, 11, 105, 8, 768, 418, 10, 292, 33, 642, 404, 769, 16, 2],
 [1, 770, 771, 16, 72, 139, 11, 139, 212, 10, 2],
 [1, 69, 20, 97, 772, 773, 10, 72, 219, 92, 93, 582, 93, 11, 53, 10, 2],
 [1, 762, 10, 2],
 [1, 39, 11, 3, 16, 2],
 [1, 38, 10, 2],
 [1, 115, 776, 155, 11, 53, 141, 777, 778, 779, 16, 2],
 [1, 780, 93, 781, 11193, 10, 2],
 [1, 44, 385, 4, 490, 130, 2],
 [1, 577, 204, 481, 4, 385, 504, 130, 2],
 [1, 274, 130, 2],
 [1, 72, 100, 201, 61, 561, 783, 97, 778, 785, 10, 2],
 [1, 97, 778, 785, 292, 106, 169, 786, 787, 539, 10, 2],
 [1, 93, 24, 201, 303, 4, 11, 115, 93, 136, 789, 496, 10, 2],
 [1, 147, 10, 396, 20, 246, 130, 2],
 [1, 396, 100, 246, 130, 2],
 [1, 396, 100, 791, 93, 221, 418, 189, 10, 2],
 [1, 187, 236, 274, 334, 130, 2],
 [1, 187, 72, 26, 793, 201, 303, 10, 2],
 [1, 72, 163, 795, 4, 212, 796, 115, 270, 61, 797, 445, 577, 204, 10, 2],
 [1, 38, 4, 218, 212, 20, 95, 69, 10, 2],
 [1, 69, 100, 8, 10, 2],
 [1, 152, 418, 4, 69, 100, 577, 197, 10, 2],
 [1, 12, 4, 97, 802, 155, 97, 778, 785, 39, 8, 106, 518, 39, 110, 395, 10, 2],
 [1, 862, 292, 0, 10, 2],
 [1, 292, 212, 805, 20, 806, 16, 2],
 [1, 72, 163, 23387, 10, 2],
 [1, 762, 10, 2],
 [1, 227, 39, 11, 808, 22, 16, 2],
 [1, 490, 130, 2],
 [1, 227, 72, 163, 809, 292, 130, 2],
 [1, 446, 810, 502, 201, 97, 778, 785, 10, 2],
 [1, 97, 780, 811, 292, 385, 42, 84, 7, 8, 115, 61, 190, 93, 812, 69, 10, 2],
 [1, 218, 227, 140, 84, 285, 16, 2],
 [1,
  72,
  814,
  8,
  260,
  815,
  22,
  69,
  10,
  227,
  140,
  84,
  262,
  816,
  817,
  97,
  818,
  130,
  2],
 [1, 187, 84, 262, 812, 69, 16, 2],
 [1, 227, 140, 303, 100, 61, 190, 130, 2],
 [1, 212, 84, 262, 819, 97, 778, 785, 580, 61, 820, 393, 201, 446, 130, 2],
 [1, 218, 236, 821, 97, 778, 785, 580, 668, 393, 201, 446, 16, 2],
 [1, 106, 130, 2],
 [1, 106, 504, 274, 10, 1367, 10, 2],
 [1, 39, 11, 808, 22, 61, 446, 823, 16, 2],
 [1, 43, 10, 43, 4, 155, 170, 336, 10, 43, 4, 336, 61, 446, 823, 10, 2],
 [1, 33, 292, 216, 106, 61, 130, 2],
 [1, 38, 10, 106, 61, 446, 823, 10, 2],
 [1, 72, 139, 4, 69, 20, 826, 10, 69, 20, 826, 10, 2],
 [1, 218, 72, 814, 8, 260, 815, 22, 69, 10, 303, 20, 26, 93, 136, 130, 2],
 [1, 828, 190, 130, 2],
 [1, 69, 20, 826, 10, 762, 10, 2],
 [1, 72, 24, 830, 205, 61, 831, 130, 2],
 [1, 490, 406, 832, 826, 1508, 10, 2],
 [1, 490, 4, 59, 7, 84, 582, 93, 22, 33, 16, 2],
 [1, 834, 446, 48, 2],
 [1, 1080, 10, 2],
 [1, 1219, 836, 837, 4, 11, 54, 828, 838, 16, 2],
 [1, 839, 838, 56, 136, 840, 10, 3, 10, 2],
 [1, 11, 240, 336, 136, 841, 212, 4, 3, 16, 2],
 [1, 212, 292, 600, 155, 61, 842, 843, 844, 72, 163, 687, 152, 857, 10, 2],
 [1, 303, 11, 244, 10, 11, 815, 22, 838, 16, 2],
 [1, 72, 37, 338, 11, 61, 846, 155, 847, 6, 61, 848, 155, 849, 10, 2],
 [1, 43, 10, 212, 20, 227, 11, 54, 10, 2],
 [1, 23, 285, 11, 128, 33, 16, 2],
 [1, 851, 10, 219, 16, 2],
 [1, 183, 11, 852, 152, 69, 16, 43, 10, 2],
 [1, 72, 696, 69, 4, 754, 10, 2],
 [1, 11, 106, 15, 201, 97, 851, 4, 855, 16, 2],
 [1, 490, 713, 2334, 10, 2],
 [1, 69, 20, 253, 4, 232, 10, 857, 701, 858, 342, 72, 859, 939, 10, 2],
 [1, 490, 4, 72, 163, 134, 135, 130, 2],
 [1, 43, 10, 84, 139, 227, 69, 832, 106, 10, 2],
 [1, 365, 4, 387, 862, 11, 118, 478, 4, 292, 342, 219, 863, 16, 2],
 [1, 778, 864, 865, 237, 97, 866, 867, 130, 2],
 [1, 868, 236, 869, 97, 870, 871, 10, 37, 84, 872, 6, 212, 16, 2],
 [1, 873, 11, 10, 2],
 [1, 201, 875, 20, 876, 4, 69, 877, 11, 14, 336, 83, 761, 10, 2],
 [1, 72, 285, 10, 43, 10, 2],
 [1, 11, 879, 1361, 10, 2],
 [1, 69, 20, 61, 881, 93, 103, 476, 0, 10, 2],
 [1, 187, 42, 11, 348, 135, 221, 61, 130, 227, 7, 11, 883, 69, 16, 2],
 [1, 61, 446, 884, 16, 2],
 [1,
  38,
  4,
  61,
  446,
  884,
  10,
  155,
  170,
  10,
  523,
  285,
  8,
  84,
  757,
  155,
  33,
  504,
  16,
  2],
 [1, 145, 4, 505, 69, 20, 885, 10, 505, 69, 20, 61, 886, 256, 10, 2],
 [1,
  97,
  485,
  39,
  201,
  97,
  355,
  10,
  84,
  262,
  244,
  173,
  4,
  84,
  262,
  24,
  492,
  10,
  2],
 [1, 84, 37, 889, 373, 786, 468, 10, 84, 37, 423, 508, 173, 10, 2],

In [115]:
len(input_numerical_sentences)

36813

In [116]:
training_sequence = []
for sentence in input_numerical_sentences:
  for i in range(1, len(sentence)):
    training_sequence.append(sentence[:i+1])

In [118]:
len(training_sequence)

314695

In [119]:
training_sequence[:5]

[[1, 3], [1, 3, 4], [1, 3, 4, 5], [1, 3, 4, 5, 6], [1, 3, 4, 5, 6, 4]]

In [120]:
len_list = []

for sequence in training_sequence:
  len_list.append(len(sequence))

max(len_list)

36

In [121]:
padded_training_sequence = []
for sequence in training_sequence:

  padded_training_sequence.append([0]*(max(len_list) - len(sequence)) + sequence)

In [124]:

padded_training_sequence = torch.as_tensor(padded_training_sequence, dtype=torch.long)

X = padded_training_sequence[:, :-1]
y = padded_training_sequence[:,-1]
torch.save(X, '../artifacts/data_processing/X.pt')
torch.save(y, '../artifacts/data_processing/y.pt')

In [126]:
print(padded_training_sequence[:5])

tensor([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 3],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 3, 4],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 1, 3, 4, 5],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 1, 3, 4, 5, 6],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 1, 3, 4, 5, 6, 4]])